In [1]:
3+3

6

In [2]:
import pandas as pd

In [3]:
rows = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
list_data=pd.DataFrame(rows,columns=['a','b','c'])

In [6]:
list_data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
list_data.shape

(3, 3)

In [10]:
dict_data= {'Name':['Amit','Yash','Jay'],'Money':[1,4,5],'Finacial':[1,0,8]}
dict_data

{'Name': ['Amit', 'Yash', 'Jay'], 'Money': [1, 4, 5], 'Finacial': [1, 0, 8]}

In [11]:
pd.DataFrame(dict_data
)

   Name  Money  Finacial
0  Amit      1         1
1  Yash      4         0
2   Jay      5         8

In [12]:
data=pd.read_csv('Student Depression Dataset.csv')

In [13]:
data

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [14]:
type(data)

pandas.DataFrame

In [15]:
df=data

In [16]:
df.shape

(27901, 18)

In [17]:
df.index

RangeIndex(start=0, stop=27901, step=1)

In [18]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [19]:
df.values

array([[2, 'Male', 33.0, ..., 1.0, 'No', 1],
       [8, 'Female', 24.0, ..., 2.0, 'Yes', 0],
       [26, 'Male', 31.0, ..., 1.0, 'Yes', 0],
       ...,
       [140689, 'Male', 31.0, ..., 2.0, 'No', 0],
       [140690, 'Female', 18.0, ..., 5.0, 'No', 1],
       [140699, 'Male', 27.0, ..., 3.0, 'Yes', 1]],
      shape=(27901, 18), dtype=object)

In [20]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [21]:
df.ndim

2

In [22]:
df.size

502218

In [23]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [28]:
df[df['Age']>35]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
201,978,Female,39.0,Kalyan,Student,5.0,0.0,6.51,4.0,0.0,7-8 hours,Moderate,M.Tech,Yes,7.0,2.0,No,1
1076,5569,Female,42.0,Rajkot,Student,2.0,0.0,9.03,5.0,0.0,More than 8 hours,Moderate,Class 12,Yes,3.0,1.0,Yes,0
1330,6852,Male,36.0,Mumbai,Student,5.0,0.0,7.10,5.0,0.0,Less than 5 hours,Moderate,MSc,Yes,0.0,2.0,Yes,0
2885,14659,Female,36.0,Agra,Student,3.0,0.0,5.90,5.0,0.0,7-8 hours,Healthy,MCA,No,11.0,5.0,Yes,0
2909,14768,Female,58.0,Chennai,Student,4.0,0.0,8.58,1.0,0.0,7-8 hours,Healthy,Class 12,No,4.0,4.0,No,0
3337,16725,Female,39.0,Vadodara,Student,4.0,0.0,5.60,2.0,0.0,Less than 5 hours,Unhealthy,M.Ed,Yes,9.0,5.0,Yes,1
3436,17213,Male,49.0,Nagpur,Student,3.0,0.0,6.47,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,2.0,1.0,Yes,0
4365,21880,Male,38.0,Chennai,Student,0.0,5.0,0.00,0.0,4.0,5-6 hours,Healthy,Class 12,No,2.0,3.0,No,0
4386,22004,Female,51.0,Bhopal,Student,2.0,0.0,8.26,3.0,0.0,Less than 5 hours,Moderate,MBBS,Yes,5.0,5.0,Yes,0
5370,27101,Male,36.0,Delhi,Student,1.0,0.0,5.61,3.0,0.0,More than 8 hours,Unhealthy,B.Com,No,7.0,2.0,No,0
5537,27918,Female,44.0,Srinagar,Student,1.0,0.0,6.83,3.0,0.0,Less than 5 hours,Unhealthy,BSc,No,4.0,3.0,No,0
6576,32961,Male,38.0,Kolkata,Student,2.0,0.0,6.02,5.0,0.0,More than 8 hours,Moderate,B.Arch,No,5.0,2.0,No,0
6662,33392,Male,43.0,Rajkot,Student,5.0,0.0,5.64,2.0,0.0,5-6 hours,Moderate,B.Ed,No,9.0,4.0,Yes,1
8819,44469,Male,38.0,Patna,Student,5.0,0.0,5.74,1.0,0.0,5-6 hours,Healthy,MBBS,No,8.0,3.0,Yes,1
9006,45393,Male,46.0,Nashik,Student,1.0,0.0,6.10,3.0,0.0,7-8 hours,Unhealthy,PhD,No,4.0,2.0,No,0
9044,45599,Female,38.0,Patna,Student,5.0,0.0,5.11,4.0,0.0,Less than 5 hours,Healthy,BSc,Yes,10.0,1.0,Yes,1
9238,46602,Male,59.0,Nashik,Student,1.0,0.0,8.14,1.0,0.0,5-6 hours,Unhealthy,PhD,Yes,10.0,4.0,Yes,0
11532,58262,Male,42.0,Kolkata,Student,5.0,0.0,6.10,1.0,0.0,Less than 5 hours,Healthy,MBBS,Yes,10.0,4.0,No,1
12351,62415,Female,36.0,Kalyan,Student,1.0,0.0,9.63,5.0,0.0,5-6 hours,Moderate,B.Com,No,0.0,4.0,Yes,0
13499,68441,Male,54.0,Agra,Student,5.0,0.0,9.60,2.0,0.0,More than 8 hours,Unhealthy,B.Ed,Yes,9.0,3.0,Yes,0
13618,69032,Female,48.0,Ghaziabad,Student,3.0,0.0,7.48,5.0,0.0,More than 8 hours,Healthy,LLB,No,2.0,4.0,No,0
14739,74456,Female,38.0,Patna,Student,1.0,0.0,9.49,3.0,0.0,5-6 hours,Moderate,Class 12,No,9.0,4.0,No,0
14819,74887,Female,56.0,Ludhiana,Student,3.0,0.0,7.94,5.0,0.0,5-6 hours,Unhealthy,BSc,No,1.0,5.0,Yes,0
16757,84722,Female,43.0,Bhopal,Student,5.0,0.0,9.67,1.0,0.0,7-8 hours,Healthy,MSc,Yes,2.0,3.0,Yes,0
17917,90634,Female,37.0,Bangalore,Student,1.0,0.0,9.41,3.0,0.0,5-6 hours,Moderate,BHM,No,0.0,4.0,Yes,0
18230,92312,Female,39.0,Pune,Student,5.0,0.0,5.60,5.0,0.0,More than 8 hours,Healthy,M.Ed,No,2.0,5.0,No,0
18766,94978,Female,46.0,Lucknow,Student,3.0,0.0,6.83,1.0,0.0,5-6 hours,Healthy,MCA,No,8.0,5.0,No,1
20097,101703,Male,37.0,Surat,Student,1.0,0.0,5.41,1.0,0.0,5-6 hours,Unhealthy,BSc,Yes,1.0,5.0,Yes,0
20373,103156,Female,36.0,Visakhapatnam,Student,1.0,0.0,7.10,3.0,0.0,More than 8 hours,Unhealthy,ME,No,6.0,1.0,Yes,0
20493,103759,Female,38.0,Kalyan,Student,1.0,0.0,9.96,4.0,0.0,5-6 hours,Moderate,M.Com,Yes,9.0,3.0,No,0
22101,111622,Female,42.0,Vasai-Virar,Student,5.0,0.0,9.56,2.0,0.0,5-6 hours,Moderate,PhD,No,4.0,2.0,Yes,0
22710,114523,Female,36.0,Hyderabad,Student,3.0,0.0,8.35,3.0,0.0,5-6 hours,Healthy,Class 12,No,5.0,4.0,Yes,0
22859,115258,Male,38.0,Hyderabad,Student,3.0,0.0,8.94,2.0,0.0,7-8 hours,Healthy,M.Pharm,Yes,0.0,2.0,No,0
23414,118005,Male,42.0,Ludhiana,Student,5.0,0.0,5.32,4.0,0.0,7-8 hours,Unhealthy,Class 12,No,12.0,5.0,Yes,1
25202,126970,Female,48.0,Rajkot,Student,3.0,0.0,5.32,4.0,0.0,7-8 hours,Unhealthy,Class 12,No,1.0,4.0,Yes,1
25705,129559,Male,38.0,Meerut,Student,2.0,0.0,7.71,1.0,0.0,5-6 hours,Moderate,MBBS,No,2.0,5.0,Yes,0
25974,130893,Male,41.0,Patna,Student,3.0,0.0,5.85,1.0,0.0,5-6 hours,Moderate,Class 12,No,11.0,5.0,Yes,1
27178,137013,Male,36.0,Varanasi,Student,0.0,0.0,8.54,3.0,0.0,More than 8 hours,Moderate,Class 12,Yes,8.0,5.0,Yes,1
27334,137827,Female,48.0,Surat,Student,1.0,0.0,8.92,4.0,0.0,7-8 hours,Moderate,MD,Yes,12.0,4.0,Yes,0

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), str(8)
memory usage: 5.2 MB

In [30]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

In [32]:
df.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         3
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [33]:
df['Financial Stress'].isnull

<bound method Series.isnull of 0        1.0
1        2.0
2        1.0
3        5.0
4        1.0
        ...
27896    1.0
27897    3.0
27898    2.0
27899    5.0
27900    3.0
Name: Financial Stress, Length: 27901, dtype: float64>

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [36]:
df.rename(columns={'CGPA':'cgpa'})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [37]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [38]:
df.rename(columns={'Age':'AGE'}, inplace=True)

In [39]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [40]:
df.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [41]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [42]:
df.sum(axis=0)

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [43]:
df.min

<bound method DataFrame.min of            id  Gender   AGE           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

          Sleep Duration Dietary Habits    Degree  \
0              5-6 hours        Healthy   B.Pharm
1              5-6 hours       Moderate       BSc
2      Less than 5 hours        Healthy        BA
3              7-8 hours       Moderate       BCA
4              5-6 hours       Moderate    M.Tech
...                  ...            ...       ...
27896          5-6 hours      Unhealthy  Class 12
27897  Less than 5 hours        Healthy       MSc
27898          5-6 hours      Unhealthy        MD
27899  Less than 5 hours        Healthy  Class 12
27900  Less than 5 hours        Healthy       BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

       Financial Stress Family History of Mental Illness  Depression
0                   1.0                               No           1
1                   2.0                              Yes           0
2                   1.0                              Yes           0
3                   5.0                              Yes           1
4                   1.0                               No           0
...                 ...                              ...         ...
27896               1.0                              Yes           0
27897               3.0                              Yes           0
27898               2.0                               No           0
27899               5.0                               No           1
27900               3.0                              Yes           1

[27901 rows x 18 columns]>

In [44]:
df.min()

id                                               2
Gender                                      Female
AGE                                           18.0
City                                           3.0
Profession                               Architect
Academic Pressure                              0.0
Work Pressure                                  0.0
CGPA                                           0.0
Study Satisfaction                             0.0
Job Satisfaction                               0.0
Sleep Duration                           5-6 hours
Dietary Habits                             Healthy
Degree                                      B.Arch
Have you ever had suicidal thoughts ?           No
Work/Study Hours                               0.0
Financial Stress                               1.0
Family History of Mental Illness                No
Depression                                       0
dtype: object

In [45]:
df.max()

id                                               140699
Gender                                             Male
AGE                                                59.0
City                                      Visakhapatnam
Profession                               UX/UI Designer
Academic Pressure                                   5.0
Work Pressure                                       5.0
CGPA                                               10.0
Study Satisfaction                                  5.0
Job Satisfaction                                    4.0
Sleep Duration                                   Others
Dietary Habits                                Unhealthy
Degree                                              PhD
Have you ever had suicidal thoughts ?               Yes
Work/Study Hours                                   12.0
Financial Stress                                    5.0
Family History of Mental Illness                    Yes
Depression                                            1
dtype: object

In [46]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [47]:
df['Academic Pressure']

0        5.0
1        2.0
2        3.0
3        3.0
4        4.0
        ...
27896    5.0
27897    2.0
27898    3.0
27899    5.0
27900    4.0
Name: Academic Pressure, Length: 27901, dtype: float64

In [48]:
data1=df[['id','Gender','AGE','City']]

In [49]:
data1

           id  Gender   AGE           City
0           2    Male  33.0  Visakhapatnam
1           8  Female  24.0      Bangalore
2          26    Male  31.0       Srinagar
3          30  Female  28.0       Varanasi
4          32  Female  25.0         Jaipur
...       ...     ...   ...            ...
27896  140685  Female  27.0          Surat
27897  140686    Male  27.0       Ludhiana
27898  140689    Male  31.0      Faridabad
27899  140690  Female  18.0       Ludhiana
27900  140699    Male  27.0          Patna

[27901 rows x 4 columns]

In [50]:
df.iloc[1000]

id                                                5152
Gender                                            Male
AGE                                               29.0
City                                     Visakhapatnam
Profession                                     Student
Academic Pressure                                  3.0
Work Pressure                                      0.0
CGPA                                              7.94
Study Satisfaction                                 3.0
Job Satisfaction                                   0.0
Sleep Duration                               5-6 hours
Dietary Habits                                Moderate
Degree                                             BSc
Have you ever had suicidal thoughts ?               No
Work/Study Hours                                   2.0
Financial Stress                                   1.0
Family History of Mental Illness                   Yes
Depression                                           0
Name: 1000, dtype: object

In [51]:
df.iloc[0:10]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1

In [52]:
df.iloc[8:]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1