In [1]:
6+6

12

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('huge_1M_titanic.csv')

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [5]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [6]:
data=data.drop(columns=['PassengerId', 'Name','Age','Ticket','Cabin'])

In [7]:
data['Embarked']=data['Embarked'].replace({'S':'Southamtom','C':'Cheboung','Q':'Queensland'})

In [8]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='str')

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Survived  1000000 non-null  int64
 1   Pclass    1000000 non-null  int64
 2   Sex       1000000 non-null  str
 3   SibSp     1000000 non-null  int64
 4   Parch     1000000 non-null  int64
 5   Fare      1000000 non-null  float64
 6   Embarked  997760 non-null   str
dtypes: float64(1), int64(4), str(2)
memory usage: 67.2 MB

In [10]:
data.sample()

        Survived  Pclass     Sex  SibSp  Parch       Fare    Embarked
893853         1       1  female      1      1  53.840485  Southamtom

In [11]:
data.dropna(subset=['Embarked'], inplace=True)

In [12]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='str')

In [18]:
data.sample()

        Survived  Pclass  Sex  SibSp  Parch  Fare    Embarked
500775         1       3    1      0      0   0.0  Southamtom

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label=LabelEncoder()
ohe=OneHotEncoder(sparse_output=False)

In [17]:
data['Sex']=label.fit_transform(data['Sex'])

In [19]:
Embarked=ohe.fit_transform(data[['Embarked']])

In [20]:
Embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(997760, 3))

In [21]:
Embarked=pd.DataFrame(Embarked,columns=ohe.get_feature_names_out())

In [22]:
Embarked

        Embarked_Cheboung  Embarked_Queensland  Embarked_Southamtom
0                     1.0                  0.0                  0.0
1                     0.0                  0.0                  1.0
2                     1.0                  0.0                  0.0
3                     0.0                  0.0                  1.0
4                     1.0                  0.0                  0.0
...                   ...                  ...                  ...
997755                0.0                  0.0                  1.0
997756                0.0                  0.0                  1.0
997757                0.0                  0.0                  1.0
997758                0.0                  0.0                  1.0
997759                0.0                  0.0                  1.0

[997760 rows x 3 columns]

In [23]:
data.sample()

       Survived  Pclass  Sex  SibSp  Parch       Fare    Embarked
44849         1       1    1      0      0  47.160065  Southamtom

In [24]:
data=pd.concat([data.drop(columns=['Embarked']),Embarked],axis=1)

In [25]:
data.sample()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboung,Embarked_Queensland,Embarked_Southamtom
17866,0.0,3.0,1.0,0.0,0.0,5.435893,0.0,0.0,1.0

In [26]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()

In [28]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cheboung', 'Embarked_Queensland', 'Embarked_Southamtom'],
      dtype='str')

In [29]:
num_cols=['Pclass','SibSp',	'Parch','Fare']

In [30]:
data[num_cols]=scale.fit_transform(data[num_cols])

In [31]:
import pickle

with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label,file)
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(ohe,file)
with open('scale.pkl','wb') as file:
    pickle.dump(scale,file)

In [32]:
data.isnull().sum()

Survived               2234
Pclass                 2234
Sex                    2234
SibSp                  2234
Parch                  2234
Fare                   2234
Embarked_Cheboung      2234
Embarked_Queensland    2234
Embarked_Southamtom    2234
dtype: int64

In [33]:
data=data.dropna()

In [35]:
data.isnull().sum()

Survived               0
Pclass                 0
Sex                    0
SibSp                  0
Parch                  0
Fare                   0
Embarked_Cheboung      0
Embarked_Queensland    0
Embarked_Southamtom    0
dtype: int64

In [36]:
#Train validatiom and test

X=data.drop(columns='Survived')
Y=data['Survived']

In [38]:
#Model selection

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=20, random_state=42)

In [39]:
X_train,X_valid,Y_train,Y_valid=train_test_split(X_train,Y_train,test_size=0.2, random_state=42)

In [42]:
import tensorflow

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [45]:
(X_train.shape[1],)

(8,)

In [48]:
model=Sequential([Dense(128,input_shape=(X_train.shape[1],),activation='relu'),
            Dense(64,activation='relu'),
            Dense(32,activation='relu'),Dense(1,activation='sigmoid')])

In [50]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,521 (45.00 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
#Model compliation optimizer, loss, metrics

In [52]:
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [53]:
tensorflow.keras.losses.binary_crossentropy

In [54]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [58]:
stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [59]:
model.fit(X_train,Y_train,validation_data=(X_valid,Y_valid), epochs=3,callbacks=[stopping_callback])

Epoch 1/3
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 120s 5ms/step - accuracy: 0.8534 - loss: 0.3338 - val_accuracy: 0.8549 - val_loss: 0.3307
Epoch 2/3
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 119s 5ms/step - accuracy: 0.8543 - loss: 0.3320 - val_accuracy: 0.8564 - val_loss: 0.3323
Epoch 3/3
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 97s 4ms/step - accuracy: 0.8539 - loss: 0.3320 - val_accuracy: 0.8559 - val_loss: 0.3293

In [60]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.