In [1]:
6+6

12

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('huge_1M_titanic.csv')

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [5]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [6]:
data=data.drop(columns=['PassengerId', 'Name','Age','Ticket','Cabin'])

In [7]:
data['Embarked']=data['Embarked'].replace({'S':'Southamtom','C':'Cheboung','Q':'Queensland'})

In [8]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='str')

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Survived  1000000 non-null  int64
 1   Pclass    1000000 non-null  int64
 2   Sex       1000000 non-null  str
 3   SibSp     1000000 non-null  int64
 4   Parch     1000000 non-null  int64
 5   Fare      1000000 non-null  float64
 6   Embarked  997760 non-null   str
dtypes: float64(1), int64(4), str(2)
memory usage: 67.2 MB

In [10]:
data.sample()

        Survived  Pclass     Sex  SibSp  Parch       Fare    Embarked
893853         1       1  female      1      1  53.840485  Southamtom

In [11]:
data.dropna(subset=['Embarked'], inplace=True)

In [12]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='str')

In [13]:
data.sample()

        Survived  Pclass   Sex  SibSp  Parch       Fare    Embarked
554223         0       2  male      0      0  39.063483  Southamtom

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label=LabelEncoder()
ohe=OneHotEncoder(sparse_output=False)