In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('titanic_clean.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    str
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Embarked     891 non-null    str
 7   Title        891 non-null    str
 8   GrpSize      891 non-null    str
 9   FareCat      891 non-null    str
 10  AgeCat       891 non-null    str
dtypes: int64(5), str(6)
memory usage: 97.2 KB

In [4]:
df

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,1,0,3,male,1,0,S,Mr,couple,0-10,16-32
1,2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
2,3,1,3,female,0,0,S,Miss,solo,0-10,16-32
3,4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
4,138,0,1,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
886,885,0,3,male,0,0,S,Mr,solo,0-10,16-32
887,887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,888,1,1,female,0,0,S,Miss,solo,25-40,16-32
889,890,1,1,male,0,0,C,Mr,solo,25-40,16-32
890,891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [5]:
pd.read_csv('titanic_clean.csv', names=['PassengerId',	'Survived',	'Pclass','Gender',	'SibSp'	,'Parch',	'Embarked',	'Title',	'GrpSize'	,'FareCat'	,'AgeCat'])

,PassengerId,Survived,Pclass,Gender,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
1,1,0,3,male,1,0,S,Mr,couple,0-10,16-32
2,2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
3,3,1,3,female,0,0,S,Miss,solo,0-10,16-32
4,4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
887,885,0,3,male,0,0,S,Mr,solo,0-10,16-32
888,887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
889,888,1,1,female,0,0,S,Miss,solo,25-40,16-32
890,890,1,1,male,0,0,C,Mr,solo,25-40,16-32
891,891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [8]:
pd.read_csv('titanic_clean.csv', header=0)

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,1,0,3,male,1,0,S,Mr,couple,0-10,16-32
1,2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
2,3,1,3,female,0,0,S,Miss,solo,0-10,16-32
3,4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
4,138,0,1,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
886,885,0,3,male,0,0,S,Mr,solo,0-10,16-32
887,887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,888,1,1,female,0,0,S,Miss,solo,25-40,16-32
889,890,1,1,male,0,0,C,Mr,solo,25-40,16-32
890,891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [9]:
pd.read_csv('titanic_clean.csv', index_col='PassengerId')

,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
PassengerId,,,,,,,,,,
1,0,3,male,1,0,S,Mr,couple,0-10,16-32
2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
3,1,3,female,0,0,S,Miss,solo,0-10,16-32
4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
138,0,1,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...
885,0,3,male,0,0,S,Mr,solo,0-10,16-32
887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,1,1,female,0,0,S,Miss,solo,25-40,16-32
890,1,1,male,0,0,C,Mr,solo,25-40,16-32
891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [10]:
pd.read_csv('titanic_clean.csv', encoding='latin-1')

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,1,0,3,male,1,0,S,Mr,couple,0-10,16-32
1,2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
2,3,1,3,female,0,0,S,Miss,solo,0-10,16-32
3,4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
4,138,0,1,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
886,885,0,3,male,0,0,S,Mr,solo,0-10,16-32
887,887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,888,1,1,female,0,0,S,Miss,solo,25-40,16-32
889,890,1,1,male,0,0,C,Mr,solo,25-40,16-32
890,891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [11]:
pd.read_csv('titanic_clean.csv', on_bad_lines='skip')

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,1,0,3,male,1,0,S,Mr,couple,0-10,16-32
1,2,1,1,female,1,0,C,Mrs,couple,70-100,32-48
2,3,1,3,female,0,0,S,Miss,solo,0-10,16-32
3,4,1,1,female,1,0,S,Mrs,couple,40-70,32-48
4,138,0,1,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
886,885,0,3,male,0,0,S,Mr,solo,0-10,16-32
887,887,0,2,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,888,1,1,female,0,0,S,Miss,solo,25-40,16-32
889,890,1,1,male,0,0,C,Mr,solo,25-40,16-32
890,891,0,3,male,0,0,Q,Mr,solo,0-10,16-32

In [12]:
pd.read_csv('titanic_clean.csv', dtype={'Pclass':float, 'Survived':float})

,PassengerId,Survived,Pclass,Sex,SibSp,Parch,Embarked,Title,GrpSize,FareCat,AgeCat
0,1,0.0,3.0,male,1,0,S,Mr,couple,0-10,16-32
1,2,1.0,1.0,female,1,0,C,Mrs,couple,70-100,32-48
2,3,1.0,3.0,female,0,0,S,Miss,solo,0-10,16-32
3,4,1.0,1.0,female,1,0,S,Mrs,couple,40-70,32-48
4,138,0.0,1.0,male,1,0,S,Mr,couple,40-70,32-48
...,...,...,...,...,...,...,...,...,...,...,...
886,885,0.0,3.0,male,0,0,S,Mr,solo,0-10,16-32
887,887,0.0,2.0,male,0,0,S,Rare Title,solo,Oct-25,16-32
888,888,1.0,1.0,female,0,0,S,Miss,solo,25-40,16-32
889,890,1.0,1.0,male,0,0,C,Mr,solo,25-40,16-32
890,891,0.0,3.0,male,0,0,Q,Mr,solo,0-10,16-32

In [15]:
pd.read_csv('Chocolate1.csv',parse_dates=['Date'])

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-01-2022,5320,180
1,Van Tuxwell,India,85% Dark Bars,01-08-2022,7896,94
2,Gigi Bohling,India,Peanut Butter Cubes,07-07-2022,4501,91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-04-2022,12726,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-02-2022,13685,184
...,...,...,...,...,...,...
3277,Karlen McCaffrey,Australia,Spicy Special Slims,17-05-2024,5304,354
3278,Jehu Rudeforth,USA,White Choc,07-06-2024,7339,121
3279,Ches Bonnell,Canada,Organic Choco Syrup,26-07-2024,616,238
3280,Dotty Strutley,India,Eclairs,28-07-2024,2505,397
3281,Karlen McCaffrey,India,70% Dark Bites,23-05-2024,5916,355

In [16]:
pd.read_csv('titanic_clean.csv', converters={'Embarked':station})

NameError: name 'station' is not defined

In [18]:
df=pd.read_csv('Student Depression Dataset.csv', chunksize=5000)

In [19]:
for chunk in df:
    print(chunk.shape)

(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(2901, 18)

In [20]:
### Json and sql

In [1]:
import pandas as pd

In [2]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [3]:
import mysql.connector

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if group is 'connector_python':
c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\mysql\connector\optionfiles.py:98: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if group is 'connector_python':

In [4]:
data=mysql.connector.connect(host='localhost', user='root', password='', database='world')

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)

In [5]:
pd.read_sql_query('select * from city', data)

NameError: name 'data' is not defined

In [6]:
pd.read_sql_query('select * from city where population > 40000', data)

NameError: name 'data' is not defined

In [7]:
pd.read_sql_query('select * from city where District like Kabol', data)

NameError: name 'data' is not defined

In [8]:
#API

In [9]:
https://api.themoviedb.org/3/genre/movie/list?api_key=0872036ae7c241b5db1d28a993f34d52&language=en

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (2800719970.py, line 1)

In [10]:
import requests

In [13]:
response=requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=0872036ae7c241b5db1d28a993f34d52&language=en')

In [14]:
response

In [15]:
url = 'https://api.themoviedb.org/3/genre/movie/list?api_key=0872036ae7c241b5db1d28a993f34d52&language=en'
headers = {
    "accept":"application/json",
    "Authorization":"dff"
}

In [16]:
response1=requests.get(url=url, headers=headers)
print(response1)

<Response [200]>