In [1]:
6+6

12

In [2]:
import pandas as pd

In [3]:
d=pd.read_csv('train_data_cleaning.csv')

In [4]:
d.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1

In [5]:
d['text'].str.lower()

0       our deeds are the reason of this  # earthquake...
1                forest fire near la ronge sask .  canada
2       all residents asked to  ' shelter in place '  ...
3       13,000 people receive  # wildfires evacuation ...
4       just got sent this photo from ruby  # alaska a...
                              ...
7608    two giant cranes holding a bridge collapse int...
7609     @ aria ahrary  @ thetawniest the out of contr...
7610    m1 . 94  [ 01 : 04 utc ]  ? 5km s of volcano h...
7611    police investigating after an e - bike collide...
7612    the latest :  more homes razed by northern cal...
Name: text, Length: 7613, dtype: str

In [6]:
d.columns

Index(['id', 'keyword', 'location', 'text', 'target'], dtype='str')

In [7]:
text="<h1>hello i am amit kumar</h1>"

In [8]:
import re

In [9]:
re.sub(r'<.*?>',"",text)

'hello i am amit kumar'

In [10]:
def html_removal(text):
    empty_html=[]
    for i in text:
        empty_html.append(re.sub(r'<.*?>',"",i))
    return

In [16]:
text = "hey https://akashkarma.com, fdsjpogdgjpfdgds https://abc.com dfdsfds"

In [13]:
re.sub(r'https?://\S+|www\.\S+',"  ",text)

'hey    fdsjpogdgjpfdgds    dfdsfds'

In [17]:
def url_removal(text):
    return re.sub(r'https?://\S+|www\.\S+',"" , text)

In [18]:
def remove_punctuations(text):
    without_punc=[]
    return re.sub(r'[^\w\s]',"",text)

In [32]:
slang_dict={'asap':'as soon as possible', "gn":"good night", "lol":'laugh out loud'}

In [33]:
slang=pd.DataFrame({"slang":['Hey call me asap',"hi gn","lol very funnny"]})

In [34]:
text="Hey can me asap"

In [35]:
def expand_slang(text,slang_dict):
    words=text.split()
    return " ".join([slang_dict.get(word,word) for word in words])

In [36]:
expand_slang(text,slang_dict)

'Hey can me as soon as possible'

In [2]:
from textblob import TextBlob

In [3]:
text = "daili i wokout in teh eve"

In [4]:
textlb=TextBlob(text)

In [5]:
textlb.correct()

TextBlob("daily i lookout in the eve")

In [6]:
import nltk

In [7]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\a810557\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [8]:
from nltk.corpus import stopwords

In [9]:
eng=stopwords.words('english')

In [10]:
text="Hey, how are you i am fine i was looking for you"

In [12]:
text.split()

['Hey,',
 'how',
 'are',
 'you',
 'i',
 'am',
 'fine',
 'i',
 'was',
 'looking',
 'for',
 'you']

In [14]:
without_stops=[]
for i in text.split():
    if i in eng:
        without_stops.append("")
    else:
        without_stops.append(i)
    x=without_stops[:]
    " ".join(x)

In [15]:
without_stops

['Hey,', '', '', '', '', '', 'fine', '', '', 'looking', '', '']

In [16]:
import pandas as pd

In [17]:
d1=pd.read_csv('test_data_cleaning.csv')

In [18]:
d1.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about  # earthquake is different cities,...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN     Apocalypse lighting .   # Spokane  # wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [19]:
d1

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about # earthquake is different cities,..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting . # Spokane # wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
...,...,...,...,...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES SAFETY FASTENER...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane . My ci...
3260,10868,NaN,NaN,Green Line derailment in Chicago
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook ( HWO )
3262,10875,NaN,NaN,# City of Calgary has activated its Municipal...

In [20]:
d1.sample()

,id,keyword,location,text
266,862,bioterror,Springfield Tn,FedEx no longer will transport bioterror germs...

In [21]:
d1['text'].isnull().sum()

np.int64(0)

In [22]:
def stopwords(text):
    li=[]
    for i in text.split():
        if i in eng:
            li.append("")
        else:
            li.append(i)
    x=li[:]
    li.clear()
    return " ".join(x)

In [23]:
d1['text'].apply(stopwords)

0                       Just happened  terrible car crash
1       Heard  # earthquake  different cities, stay sa...
2          forest fire  spot pond, geese  fleeing acro...
3             Apocalypse lighting . # Spokane # wildfires
4                Typhoon Soudelor kills 28  China  Taiwan
                              ...
3258    EARTHQUAKE SAFETY LOS ANGELES SAFETY FASTENERS...
3259    Storm  RI worse  last hurricane . My city & 3 ...
3260                       Green Line derailment  Chicago
3261         MEG issues Hazardous Weather Outlook ( HWO )
3262    # City  Calgary  activated  Municipal Emergenc...
Name: text, Length: 3263, dtype: str

In [2]:
## BASIC TEXT PREPROCESSING

In [3]:
import pandas as pd

In [4]:
d=pd.read_csv('test_data_cleaning.csv')

In [5]:
sent="i am going to indore city"

In [6]:
sent.split()

['i', 'am', 'going', 'to', 'indore', 'city']

In [7]:
para="fdshgdgfdgfd.g fsgfdhfshfdgdhddg.dgfdhdgsdsgd.dsffdhsdhdsgfdhd."

In [8]:
para.split('.')

['fdshgdgfdgfd', 'g fsgfdhfshfdgdhddg', 'dgfdhdgsdsgd', 'dsffdhsdhdsgfdhd', '']

In [9]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [10]:
import nltk

In [11]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\a810557\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [12]:
sent=" i have pHD in AI"

In [13]:
word_tokenize(sent)

['i', 'have', 'pHD', 'in', 'AI']

In [14]:
sent_2 = "we ate dal chawal in Indore"

In [15]:
word_tokenize(sent_2)

['we', 'ate', 'dal', 'chawal', 'in', 'Indore']

In [16]:
import spacy

In [17]:
from spacy.cli import download

In [18]:
download("en_core_web_sm")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [19]:
nlp = spacy.load('en_core_web_sm')

In [20]:
text='a 5km ride cost us $30'

In [21]:
token=nlp(text)

In [22]:
for i in token:
    print(i)

a
5
km
ride
cost
us
$
30

In [23]:
#stemming

from nltk.stem import PorterStemmer

In [24]:
ps=PorterStemmer()

In [25]:
words=['running','Stories','running']

In [26]:
for i in words:
    print(ps.stem(i))

run
stori
run

In [27]:
word=['walking','walker']

In [29]:
for i in word:
    print(ps.stem(i))

walk
walker

In [30]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\a810557\AppData\Roaming\nltk_data...

True

In [31]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\a810557\AppData\Roaming\nltk_data...

True

In [32]:
lemmatizer=WordNetLemmatizer()

In [33]:
lemmatizer.lemmatize('running', pos='v')

'run'

In [34]:
lemmatizer.lemmatize('better', pos='a')

'good'

In [36]:
lemmatizer.lemmatize('mice', pos='n')

'mouse'

In [37]:
#Vector

In [46]:
import pandas as pd

In [52]:
movie=pd.read_csv('IMDB Dataset.csv')

In [53]:
movie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [54]:
movie['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [55]:
movie

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [56]:
movie.shape

(50000, 2)

In [57]:
len(movie['review'][0].split())

307

In [58]:
d=pd.DataFrame({'col':['People love AI','AI Love data','data Love Love', 'Love People People']})

In [59]:
d

                  col
0      People love AI
1        AI Love data
2      data Love Love
3  Love People People

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
cv=CountVectorizer()

In [63]:
cv.fit_transform(d['col'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (4, 4)>

In [64]:
cv.fit_transform(d['col']).toarray()

array([[1, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 0, 1, 2]])

In [66]:
cv.vocabulary_

{'people': 3, 'love': 2, 'ai': 0, 'data': 1}

In [67]:
len(cv.vocabulary_)

4

In [68]:
test=pd.DataFrame({'col':['The movie is very good','The movie is not very good']})

In [69]:
cv.fit_transform(test['col']).toarray()

array([[1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [71]:
cv=CountVectorizer(ngram_range=(2,2))

In [72]:
cv.fit_transform(test['col']).toarray()

array([[0, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1]])

In [73]:
cv.vocabulary_

{'the movie': 4,
 'movie is': 2,
 'is very': 1,
 'very good': 5,
 'is not': 0,
 'not very': 3}

In [75]:
#TF-IDF

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
tf=TfidfVectorizer()

In [78]:
d

                  col
0      People love AI
1        AI Love data
2      data Love Love
3  Love People People

In [79]:
tf.fit_transform(d['col']).toarray()

array([[0.64043405, 0.        , 0.42389674, 0.64043405],
       [0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.        , 0.60276058, 0.7979221 , 0.        ],
       [0.        , 0.        , 0.31418628, 0.94936136]])

In [80]:
tf.get_feature_names_out()

array(['ai', 'data', 'love', 'people'], dtype=object)

In [81]:
tf.idf_

array([1.51082562, 1.51082562, 1.        , 1.51082562])

In [83]:
## WORD2VEC

In [84]:
with open('harrypotter_dataset.txt', 'rt') as b1:
    h1=b1.read()

In [85]:
h1

'Title, Book index, Book release year, No. of chapters, Author, Original illustrator, Children\'s edition illustrator, Illustrated edition illustrator, House edition illustrator, Paperback edition illustrator, Movie index, Producer, Director, Screenwriter, Composer, Cinematopher, Set design, Visual effects, UK Movie relase date, US Movie release date, Runtime (in minutes), Budget, Box office gross\nHarry Potter and the (Philospher\'s) Sorcerer\'s Stone, 1, 1997, 17, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 1, David Heyman, Steve Kloves, John Williams, John Seale, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2001-11-10, 2001-11-16, 152, $125000000, $1018000000\nHarry Potter and the Chamber of Secrets, 2, 1998, 18, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 2, David Heyman, Steve Kloves, John Williams, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2002-11-15, 2002-11-15, 161, $100000000, $879600000\nHarry Potter and the Prisoner of Azkaban, 3, 1999, 22, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 3, """David Heyman"", ""Chris Columbus"", ""Mark Radcliffe""", Steve Kloves, John Williams, Michael Seresin, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative""", 2004-05-31, 2004-06-04, 144, $130000000, $797400000\nHarry Potter and the Goblet of Fire, 4, 2000, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 4, David Heyman, Steve Kloves, Patrick Doyle, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2005-11-18, 2005-11-18, 157, $150000000, $896700000\nHarry Potter and the Order of the Phoenix, 5, 2003, 38, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 5, """David Heyman"", ""David Barron""", Michael Goldenberg, Nicholas Hooper, Slawomir Idziak, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2007-07-12, 2007-07-11, 138, $200000000, $942200000\nHarry Potter and the Half-blood Prince, 6, 2005, 30, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 6, """David Heyman"", ""David Barron""", Steve Kloves, Nicholas Hooper, Bruno Delbonne, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2009-07-15, 2009-07-15, 153, $250000000, $934500000\nHarry Potter and the Deathly Hallows 1, 7, 2007, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 7, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandre Desplat, Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2010-11-19, 2010-11-19, 146, $250000000, $977000000\nHarry Potter and the Deathly Hallows 2, 7, 2007, 37,  J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 8, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandrew Desplat,Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2011-07-15, 2011-07-15, 130, $250000000, $1342000000'

In [86]:
with open('harrypotter_dataset - Copy.txt', 'rt') as b2:
    h2=b2.read()

In [87]:
h2

'Title, Book index, Book release year, No. of chapters, Author, Original illustrator, Children\'s edition illustrator, Illustrated edition illustrator, House edition illustrator, Paperback edition illustrator, Movie index, Producer, Director, Screenwriter, Composer, Cinematopher, Set design, Visual effects, UK Movie relase date, US Movie release date, Runtime (in minutes), Budget, Box office gross\nHarry Potter and the (Philospher\'s) Sorcerer\'s Stone, 1, 1997, 17, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 1, David Heyman, Steve Kloves, John Williams, John Seale, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2001-11-10, 2001-11-16, 152, $125000000, $1018000000\nHarry Potter and the Chamber of Secrets, 2, 1998, 18, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 2, David Heyman, Steve Kloves, John Williams, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2002-11-15, 2002-11-15, 161, $100000000, $879600000\nHarry Potter and the Prisoner of Azkaban, 3, 1999, 22, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 3, """David Heyman"", ""Chris Columbus"", ""Mark Radcliffe""", Steve Kloves, John Williams, Michael Seresin, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative""", 2004-05-31, 2004-06-04, 144, $130000000, $797400000\nHarry Potter and the Goblet of Fire, 4, 2000, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 4, David Heyman, Steve Kloves, Patrick Doyle, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2005-11-18, 2005-11-18, 157, $150000000, $896700000\nHarry Potter and the Order of the Phoenix, 5, 2003, 38, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 5, """David Heyman"", ""David Barron""", Michael Goldenberg, Nicholas Hooper, Slawomir Idziak, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2007-07-12, 2007-07-11, 138, $200000000, $942200000\nHarry Potter and the Half-blood Prince, 6, 2005, 30, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 6, """David Heyman"", ""David Barron""", Steve Kloves, Nicholas Hooper, Bruno Delbonne, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2009-07-15, 2009-07-15, 153, $250000000, $934500000\nHarry Potter and the Deathly Hallows 1, 7, 2007, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 7, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandre Desplat, Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2010-11-19, 2010-11-19, 146, $250000000, $977000000\nHarry Potter and the Deathly Hallows 2, 7, 2007, 37,  J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 8, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandrew Desplat,Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2011-07-15, 2011-07-15, 130, $250000000, $1342000000'

In [88]:
data=h1+h2

In [89]:
len(data.split())

909

In [90]:
from nltk import sent_tokenize

In [91]:
from gensim.utils import simple_preprocess

ModuleNotFoundError: No module named 'gensim'

In [92]:
potter=[]

In [93]:
data=sent_tokenize(data)

In [94]:
data

['Title, Book index, Book release year, No.',
 'of chapters, Author, Original illustrator, Children\'s edition illustrator, Illustrated edition illustrator, House edition illustrator, Paperback edition illustrator, Movie index, Producer, Director, Screenwriter, Composer, Cinematopher, Set design, Visual effects, UK Movie relase date, US Movie release date, Runtime (in minutes), Budget, Box office gross\nHarry Potter and the (Philospher\'s) Sorcerer\'s Stone, 1, 1997, 17, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 1, David Heyman, Steve Kloves, John Williams, John Seale, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2001-11-10, 2001-11-16, 152, $125000000, $1018000000\nHarry Potter and the Chamber of Secrets, 2, 1998, 18, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 2, David Heyman, Steve Kloves, John Williams, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2002-11-15, 2002-11-15, 161, $100000000, $879600000\nHarry Potter and the Prisoner of Azkaban, 3, 1999, 22, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 3, """David Heyman"", ""Chris Columbus"", ""Mark Radcliffe""", Steve Kloves, John Williams, Michael Seresin, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative""", 2004-05-31, 2004-06-04, 144, $130000000, $797400000\nHarry Potter and the Goblet of Fire, 4, 2000, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 4, David Heyman, Steve Kloves, Patrick Doyle, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2005-11-18, 2005-11-18, 157, $150000000, $896700000\nHarry Potter and the Order of the Phoenix, 5, 2003, 38, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 5, """David Heyman"", ""David Barron""", Michael Goldenberg, Nicholas Hooper, Slawomir Idziak, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2007-07-12, 2007-07-11, 138, $200000000, $942200000\nHarry Potter and the Half-blood Prince, 6, 2005, 30, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 6, """David Heyman"", ""David Barron""", Steve Kloves, Nicholas Hooper, Bruno Delbonne, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2009-07-15, 2009-07-15, 153, $250000000, $934500000\nHarry Potter and the Deathly Hallows 1, 7, 2007, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 7, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandre Desplat, Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2010-11-19, 2010-11-19, 146, $250000000, $977000000\nHarry Potter and the Deathly Hallows 2, 7, 2007, 37,  J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 8, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandrew Desplat,Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2011-07-15, 2011-07-15, 130, $250000000, $1342000000Title, Book index, Book release year, No.',
 'of chapters, Author, Original illustrator, Children\'s edition illustrator, Illustrated edition illustrator, House edition illustrator, Paperback edition illustrator, Movie index, Producer, Director, Screenwriter, Composer, Cinematopher, Set design, Visual effects, UK Movie relase date, US Movie release date, Runtime (in minutes), Budget, Box office gross\nHarry Potter and the (Philospher\'s) Sorcerer\'s Stone, 1, 1997, 17, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 1, David Heyman, Steve Kloves, John Williams, John Seale, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2001-11-10, 2001-11-16, 152, $125000000, $1018000000\nHarry Potter and the Chamber of Secrets, 2, 1998, 18, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 2, David Heyman, Steve Kloves, John Williams, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic""", 2002-11-15, 2002-11-15, 161, $100000000, $879600000\nHarry Potter and the Prisoner of Azkaban, 3, 1999, 22, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 3, """David Heyman"", ""Chris Columbus"", ""Mark Radcliffe""", Steve Kloves, John Williams, Michael Seresin, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative""", 2004-05-31, 2004-06-04, 144, $130000000, $797400000\nHarry Potter and the Goblet of Fire, 4, 2000, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 4, David Heyman, Steve Kloves, Patrick Doyle, Roger Pratt, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2005-11-18, 2005-11-18, 157, $150000000, $896700000\nHarry Potter and the Order of the Phoenix, 5, 2003, 38, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 5, """David Heyman"", ""David Barron""", Michael Goldenberg, Nicholas Hooper, Slawomir Idziak, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2007-07-12, 2007-07-11, 138, $200000000, $942200000\nHarry Potter and the Half-blood Prince, 6, 2005, 30, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 6, """David Heyman"", ""David Barron""", Steve Kloves, Nicholas Hooper, Bruno Delbonne, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2009-07-15, 2009-07-15, 153, $250000000, $934500000\nHarry Potter and the Deathly Hallows 1, 7, 2007, 37, J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 7, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandre Desplat, Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2010-11-19, 2010-11-19, 146, $250000000, $977000000\nHarry Potter and the Deathly Hallows 2, 7, 2007, 37,  J.K. Rowling, Mary GrandPrÃ©, Jonny Duddle, Jim Kay, Levi Pinfold, Andrew Davidson, 8, """David Heyman"", ""David Barron"", ""J.K. Rowling""", Steve Kloves, Alexandrew Desplat,Eduardo Serra, """Stuart Craig"", ""Stephenie McMillan""", """Cinesite"", ""Framestore"", ""Industrial Light & Magic"", ""Double Negative"", ""Rising Sun""", 2011-07-15, 2011-07-15, 130, $250000000, $1342000000']

In [95]:
len{data}

SyntaxError: invalid syntax (2790122262.py, line 1)

In [96]:
len(data)

3

In [ ]:
from bertopic import simple_preprocess

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm