In [1]:
7-7

0

In [67]:
import pandas as pd

In [68]:
data=pd.read_csv('twitter_training.csv')

In [69]:
data.shape

(74681, 4)

In [70]:
data=data.sample(10000, random_state=42)

In [71]:
data['Tweets']=data['im getting on borderlands and i will murder you all ,']

In [72]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,",Tweets
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one,one
...,...,...,...,...,...
5763,191,Amazon,Neutral,@OtakuWeeb11 Thanks for entering Grand Summone...,@OtakuWeeb11 Thanks for entering Grand Summone...
6213,269,Amazon,Positive,Couldn't agree some more. It'S s excellent.,Couldn't agree some more. It'S s excellent.
12347,8523,NBA2K,Negative,Soooo no token market update for the rest of t...,Soooo no token market update for the rest of t...
2515,1639,CallOfDutyBlackopsColdWar,Positive,"For anyone jumping into this Beta weekend, I h...","For anyone jumping into this Beta weekend, I h..."
57264,11423,TomClancysRainbowSix,Neutral,Week 1. Perfection MTG.. ---------------------...,Week 1. Perfection MTG.. ---------------------...

In [73]:
data['Positive'].value_counts()

Positive
Negative      3022
Positive      2832
Neutral       2353
Irrelevant    1793
Name: count, dtype: int64

In [74]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    101
Tweets                                                   101
dtype: int64

In [75]:
data.duplicated().sum()

np.int64(56)

In [76]:
data=data.dropna()

In [77]:
data.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
Tweets                                                   0
dtype: int64

In [78]:
data.drop_duplicates(inplace=True)

In [79]:
data.duplicated().sum()

np.int64(0)

In [80]:
data.drop(columns=['2401','Borderlands'], inplace=True)

In [81]:
data.drop(columns=['im getting on borderlands and i will murder you all ,'], inplace=True)

In [82]:
data.sample()

       Positive                                             Tweets
16537  Negative  My girlfriend stumbled over the price of a new...

In [83]:
data.rename(columns={'Positive':'Sentiment','i am getting on borderlands and i will murder you all':'Tweets'}, inplace=True)

In [84]:
data

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
5763      Neutral  @OtakuWeeb11 Thanks for entering Grand Summone...
6213     Positive        Couldn't agree some more. It'S s excellent.
12347    Negative  Soooo no token market update for the rest of t...
2515     Positive  For anyone jumping into this Beta weekend, I h...
57264     Neutral  Week 1. Perfection MTG.. ---------------------...

[9853 rows x 2 columns]

In [85]:
data.tail()

      Sentiment                                             Tweets
5763    Neutral  @OtakuWeeb11 Thanks for entering Grand Summone...
6213   Positive        Couldn't agree some more. It'S s excellent.
12347  Negative  Soooo no token market update for the rest of t...
2515   Positive  For anyone jumping into this Beta weekend, I h...
57264   Neutral  Week 1. Perfection MTG.. ---------------------...

In [86]:
data=data[(data['Sentiment']=='Positive')| (data['Sentiment']=='Negative')|(data['Sentiment']=='Neutral')]

In [87]:
data

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...
...         ...                                                ...
5763    Neutral  @OtakuWeeb11 Thanks for entering Grand Summone...
6213   Positive        Couldn't agree some more. It'S s excellent.
12347  Negative  Soooo no token market update for the rest of t...
2515   Positive  For anyone jumping into this Beta weekend, I h...
57264   Neutral  Week 1. Perfection MTG.. ---------------------...

[8094 rows x 2 columns]

In [88]:
data['Sentiment'].value_counts()

Sentiment
Negative    2982
Positive    2795
Neutral     2317
Name: count, dtype: int64

In [89]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [90]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [91]:
data.sample()

       Sentiment                                             Tweets
71899          0  @ GhostRecon servers are down. Trying to conne...

In [92]:
import keras

In [93]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [94]:
tokenizer=Tokenizer(oov_token='Nothing')

In [95]:
tokenizer.fit_on_texts(data['Tweets'])

In [96]:
data.sample()

       Sentiment                                             Tweets
24304          1  Superintendent Dr. Bill Nolte believes about 4...

In [97]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'have': 21,
 'me': 22,
 'be': 23,
 'just': 24,
 'not': 25,
 'was': 26,
 'are': 27,
 'but': 28,
 'all': 29,
 'at': 30,
 '2': 31,
 'out': 32,
 'get': 33,
 'your': 34,
 'pic': 35,
 'twitter': 36,
 'like': 37,
 'from': 38,
 'now': 39,
 'as': 40,
 'we': 41,
 'play': 42,
 'good': 43,
 'johnson': 44,
 't': 45,
 'they': 46,
 'if': 47,
 'new': 48,
 'do': 49,
 'about': 50,
 'can': 51,
 'has': 52,
 'when': 53,
 'one': 54,
 'no': 55,
 'will': 56,
 'time': 57,
 'really': 58,
 'more': 59,
 'an': 60,
 "i'm": 61,
 'unk': 62,
 'love': 63,
 'people': 64,
 'up': 65,
 'what': 66,
 'some': 67,
 '3': 68,
 'been': 69,
 'still': 70,
 'shit': 71,
 'co': 72,
 'by': 73,
 "it's": 74,
 'why': 75,
 '’': 76,
 'or': 77,
 'how': 78,
 'amazon': 79,
 'microsoft': 80,
 'https': 81,
 'games': 82,
 'best': 83,
 'playing': 84,
 'facebook': 85,
 'because': 86,
 'dead': 87,
 'xbox': 88,
 'great': 89,
 'verizon': 90,
 '1': 91,
 'fucking': 92,
 'got': 93,
 'even': 94,
 'back': 95,
 'fuck': 96,
 'who': 97,
 'see': 98,
 'go': 99,
 'rhandlerr': 100,
 'red': 101,
 'there': 102,
 'home': 103,
 '5': 104,
 'much': 105,
 'us': 106,
 'going': 107,
 'had': 108,
 'please': 109,
 'them': 110,
 'google': 111,
 's': 112,
 'only': 113,
 "can't": 114,
 'borderlands': 115,
 'nvidia': 116,
 'fix': 117,
 'am': 118,
 'day': 119,
 'after': 120,
 'would': 121,
 'its': 122,
 'their': 123,
 'fun': 124,
 'tv': 125,
 'eamaddennfl': 126,
 'today': 127,
 'first': 128,
 'again': 129,
 'than': 130,
 'bad': 131,
 '4': 132,
 'fifa': 133,
 'over': 134,
 '2020': 135,
 'most': 136,
 'our': 137,
 'these': 138,
 'pubg': 139,
 '…': 140,
 'very': 141,
 'wait': 142,
 'make': 143,
 'never': 144,
 'also': 145,
 'here': 146,
 'then': 147,
 'thank': 148,
 'nba2k': 149,
 'every': 150,
 'twitch': 151,
 'played': 152,
 'redemption': 153,
 'rainbow6game': 154,
 'work': 155,
 'damn': 156,
 "don't": 157,
 'think': 158,
 'ps5': 159,
 'i’m': 160,
 'he': 161,
 'thanks': 162,
 'ever': 163,
 'know': 164,
 'want': 165,
 'gta': 166,
 'too': 167,
 'news': 168,
 'call': 169,
 'amazing': 170,
 'video': 171,
 'x': 172,
 'year': 173,
 'depot': 174,
 'legends': 175,
 'getting': 176,
 'last': 177,
 "i've": 178,
 'series': 179,
 'v': 180,
 'well': 181,
 'any': 182,
 'watch': 183,
 'happy': 184,
 'say': 185,
 '10': 186,
 'overwatch': 187,
 'into': 188,
 'guys': 189,
 'league': 190,
 'battlefield': 191,
 'world': 192,
 'update': 193,
 'help': 194,
 'another': 195,
 'while': 196,
 'years': 197,
 'man': 198,
 'u': 199,
 'ass': 200,
 'creed': 201,
 'looks': 202,
 'store': 203,
 'money': 204,
 'warcraft': 205,
 'youtube': 206,
 'off': 207,
 'need': 208,
 'youtu': 209,
 'big': 210,
 'black': 211,
 'right': 212,
 'did': 213,
 'win': 214,
 'down': 215,
 'fortnite': 216,
 'many': 217,
 'ghostrecon': 218,
 'being': 219,
 'his': 220,
 'live': 221,
 'should': 222,
 'team': 223,
 'always': 224,
 'finally': 225,
 'take': 226,
 'actually': 227,
 'already': 228,
 'next': 229,
 'players': 230,
 'free': 231,
 'pc': 232,
 'made': 233,
 'thing': 234,
 'via': 235,
 'look': 236,
 'duty': 237,
 'awesome': 238,
 'support': 239,
 'way': 240,
 'everyone': 241,
 'come': 242,
 'hearthstone': 243,
 'better': 244,
 'nice': 245,
 'which': 246,
 'it’s': 247,
 'something': 248,
 'such': 249,
 'health': 250,
 'buy': 251,
 'could': 252,
 'since': 253,
 'care': 254,
 'before': 255,
 'stop': 256,
 'done': 257,
 'wtf': 258,
 'other': 259,
 '20': 260,
 'playstation': 261,
 'online': 262,
 'access': 263,
 'playapex': 264,
 'oh': 265,
 'were': 266,
 'ubisoft': 267,
 'gonna': 268,
 'ly': 269,
 'wow': 270,
 'days': 271,
 'her': 272,
 'bit': 273,
 'baby': 274,
 'account': 275,
 'looking': 276,
 'keep': 277,
 'excited': 278,
 'hate': 279,
 'long': 280,
 'mobile': 281,
 'csgo': 282,
 'same': 283,
 'having': 284,
 'give': 285,
 'trying': 286,
 'lot': 287,
 'start': 288,
 'cool': 289,
 'stream': 290,
 'old': 291,
 'card': 292,
 'hey': 293,
 'everything': 294,
 'player': 295,
 '100': 296,
 '6': 297,
 'working': 298,
 'war': 299,
 'someone': 300,
 'where': 301,
 'cyberpunk': 302,
 'nothing': 303,
 'pretty': 304,
 'check': 305,
 'life': 306,
 'through': 307,
 'doing': 308,
 '7': 309,
 'absolutely': 310,
 'god': 311,
 'powder': 312,
 'him': 313,
 'top': 314,
 'service': 315,
 'phone': 316,
 'pay': 317,
 'lol': 318,
 'probably': 319,
 'company': 320,
 'those': 321,
 'm': 322,
 'super': 323,
 'use': 324,
 'night': 325,
 'dont': 326,
 'things': 327,
 'im': 328,
 'dota': 329,
 'does': 330,
 'can’t': 331,
 'hell': 332,
 'servers': 333,
 'hope': 334,
 'stupid': 335,
 'feel': 336,
 'times': 337,
 'season': 338,
 'real': 339,
 'uk': 340,
 'makes': 341,
 'yet': 342,
 'let': 343,
 "doesn't": 344,
 '2077': 345,
 'little': 346,
 'miss': 347,
 'both': 348,
 'until': 349,
 'open': 350,
 'almost': 351,
 'week': 352,
 'won': 353,
 'chance': 354,
 'worst': 355,
 'without': 356,
 'making': 357,
 'hours': 358,
 'story': 359,
 'problem': 360,
 'two': 361,
 'hard': 362,
 'release': 363,
 'cant': 364,
 'literally': 365,
 'try': 366,
 'apex': 367,
 'anyone': 368,
 'said': 369,
 'favorite': 370,
 'sure': 371,
 'own': 372,
 'show': 373,
 'find': 374,
 'against': 375,
 '0': 376,
 '19': 377,
 'full': 378,
 'minutes': 379,
 'tell': 380,
 'lost': 381,
 'assassins': 382,
 'console': 383,
 'tt': 384,
 'app': 385,
 'gets': 386,
 'business': 387,
 'stuff': 388,
 'gaming': 389,
 'few': 390,
 '21': 391,
 'fact': 392,
 'pro': 393,
 'cold': 394,
 'trash': 395,
 'ea': 396,
 'soon': 397,
 "that's": 398,
 'vaccine': 399,
 'using': 400,
 'tonight': 401,
 'far': 402,
 'idea': 403,
 "y'all": 404,
 'callofduty': 405,
 'part': 406,
 'says': 407,
 'mode': 408,
 'dota2': 409,
 'gameplay': 410,
 'ops': 411,
 'beluba': 412,
 'covid': 413,
 'perfect': 414,
 'coming': 415,
 'ranked': 416,
 'around': 417,
 'ban': 418,
 'beautiful': 419,
 'hit': 420,
 'went': 421,
 'weekend': 422,
 'crazy': 423,
 'thought': 424,
 'wrong': 425,
 'friends': 426,
 'end': 427,
 'share': 428,
 'anything': 429,
 'screen': 430,
 'whole': 431,
 "you're": 432,
 'used': 433,
 'y’all': 434,
 'madden': 435,
 'tried': 436,
 'though': 437,
 'enjoy': 438,
 'million': 439,
 'ift': 440,
 "assassin's": 441,
 'away': 442,
 'job': 443,
 'watching': 444,
 'forward': 445,
 'order': 446,
 'put': 447,
 'interesting': 448,
 'exciting': 449,
 '2k': 450,
 'talc': 451,
 '”': 452,
 "didn't": 453,
 'due': 454,
 'high': 455,
 'grand': 456,
 'currently': 457,
 'change': 458,
 'sad': 459,
 '30': 460,
 'system': 461,
 'cs': 462,
 'bought': 463,
 'price': 464,
 'ps4': 465,
 'data': 466,
 'guy': 467,
 '15': 468,
 'p': 469,
 'd': 470,
 'graphics': 471,
 'playhearthstone': 472,
 'month': 473,
 'line': 474,
 "i'll": 475,
 'customer': 476,
 'apps': 477,
 'sorry': 478,
 'maybe': 479,
 'windows': 480,
 'level': 481,
 'definitely': 482,
 'worth': 483,
 'epic': 484,
 'morning': 485,
 'second': 486,
 'kill': 487,
 'during': 488,
 'took': 489,
 'able': 490,
 'latest': 491,
 'server': 492,
 '12': 493,
 'wanted': 494,
 'services': 495,
 'skin': 496,
 'reason': 497,
 'selling': 498,
 'came': 499,
 'point': 500,
 'i’ve': 501,
 'banned': 502,
 'rewards': 503,
 'don’t': 504,
 'ok': 505,
 'problems': 506,
 'finished': 507,
 'character': 508,
 'single': 509,
 'read': 510,
 'n2k': 511,
 'might': 512,
 "haven't": 513,
 'pre': 514,
 'myteam': 515,
 'post': 516,
 'design': 517,
 'based': 518,
 'bro': 519,
 'enough': 520,
 'power': 521,
 'else': 522,
 'set': 523,
 'internet': 524,
 'run': 525,
 'gen': 526,
 'net': 527,
 'homedepot': 528,
 'despite': 529,
 'broken': 530,
 'killed': 531,
 'tomorrow': 532,
 'half': 533,
 'annoying': 534,
 'may': 535,
 'instead': 536,
 'w': 537,
 'mean': 538,
 'updates': 539,
 'org': 540,
 'eu': 541,
 'luck': 542,
 '8': 543,
 'ago': 544,
 'hour': 545,
 'content': 546,
 'saying': 547,
 'terrible': 548,
 'list': 549,
 'guess': 550,
 'ronnie2k': 551,
 'seems': 552,
 'person': 553,
 'feels': 554,
 'taken': 555,
 'don': 556,
 'teams': 557,
 'different': 558,
 'cards': 559,
 'music': 560,
 'breakpoint': 561,
 'trailer': 562,
 'blizzard': 563,
 'experience': 564,
 'wanna': 565,
 'later': 566,
 'comes': 567,
 'leagueoflegends': 568,
 'e': 569,
 'shot': 570,
 'huge': 571,
 'must': 572,
 'believe': 573,
 'face': 574,
 'hear': 575,
 'needs': 576,
 'she': 577,
 'yall': 578,
 'funny': 579,
 'match': 580,
 'warzone': 581,
 "won't": 582,
 'yo': 583,
 'holy': 584,
 'late': 585,
 'major': 586,
 'myself': 587,
 'completely': 588,
 'cod': 589,
 'seen': 590,
 'products': 591,
 'name': 592,
 'iphone': 593,
 'patch': 594,
 '“': 595,
 'sucks': 596,
 'least': 597,
 'gone': 598,
 'r': 599,
 'sometimes': 600,
 'seriously': 601,
 'proud': 602,
 'anymore': 603,
 'ready': 604,
 'together': 605,
 'cause': 606,
 'worse': 607,
 'totally': 608,
 'early': 609,
 'gold': 610,
 'review': 611,
 'suck': 612,
 'started': 613,
 'event': 614,
 'die': 615,
 'months': 616,
 'living': 617,
 'below': 618,
 'drop': 619,
 'sound': 620,
 'pass': 621,
 'hello': 622,
 'y': 623,
 'achievement': 624,
 'movie': 625,
 '3080': 626,
 'yes': 627,
 'fan': 628,
 'stay': 629,
 'step': 630,
 'apple': 631,
 'seeing': 632,
 'loved': 633,
 'error': 634,
 'leave': 635,
 'complete': 636,
 'smh': 637,
 'three': 638,
 're': 639,
 '9': 640,
 'edition': 641,
 've': 642,
 'gift': 643,
 'number': 644,
 'under': 645,
 'bugs': 646,
 'community': 647,
 'girl': 648,
 'lmao': 649,
 'fps': 650,
 'dlvr': 651,
 'garbage': 652,
 'friend': 653,
 'running': 654,
 'keeps': 655,
 'add': 656,
 'bring': 657,
 'mind': 658,
 'code': 659,
 'moment': 660,
 'understand': 661,
 'launch': 662,
 'switch': 663,
 'city': 664,
 'canada': 665,
 'weeks': 666,
 'book': 667,
 'class': 668,
 'thinking': 669,
 'truly': 670,
 'found': 671,
 'join': 672,
 'yesterday': 673,
 'india': 674,
 'birthday': 675,
 'sick': 676,
 'honestly': 677,
 'continue': 678,
 'market': 679,
 'rtx': 680,
 'hi': 681,
 'streaming': 682,
 'omg': 683,
 'received': 684,
 'retweet': 685,
 'easports': 686,
 'means': 687,
 'remember': 688,
 "they're": 689,
 'family': 690,
 'ghost': 691,
 'sold': 692,
 'earned': 693,
 'c': 694,
 'technology': 695,
 'playoverwatch': 696,
 'yeah': 697,
 'incredible': 698,
 'bullshit': 699,
 'users': 700,
 'taking': 701,
 'mad': 702,
 'tho': 703,
 'house': 704,
 'id': 705,
 'follow': 706,
 'plz': 707,
 'released': 708,
 'en': 709,
 'insane': 710,
 'global': 711,
 'talk': 712,
 'bug': 713,
 'issues': 714,
 'trust': 715,
 'quite': 716,
 'warfare': 717,
 'issue': 718,
 'main': 719,
 'trump': 720,
 'daily': 721,
 'listen': 722,
 '–': 723,
 'battle': 724,
 'that’s': 725,
 'kills': 726,
 'small': 727,
 'waiting': 728,
 'place': 729,
 'past': 730,
 'easy': 731,
 'cannot': 732,
 'action': 733,
 'instagram': 734,
 'buying': 735,
 'spent': 736,
 'tired': 737,
 'channel': 738,
 'tech': 739,
 'decision': 740,
 'commission': 741,
 'hot': 742,
 "what's": 743,
 'once': 744,
 'coronavirus': 745,
 'joke': 746,
 'lots': 747,
 'men': 748,
 'article': 749,
 'ur': 750,
 'steam': 751,
 'move': 752,
 'link': 753,
 'left': 754,
 'each': 755,
 'wild': 756,
 'either': 757,
 'videos': 758,
 'worked': 759,
 '11': 760,
 'saw': 761,
 'original': 762,
 'l': 763,
 'search': 764,
 'b': 765,
 'women': 766,
 'paid': 767,
 'died': 768,
 'goes': 769,
 'knows': 770,
 'called': 771,
 'turn': 772,
 'points': 773,
 'glad': 774,
 "there's": 775,
 'deal': 776,
 'rockstargames': 777,
 'sales': 778,
 'cute': 779,
 'digital': 780,
 'death': 781,
 'f': 782,
 'bitch': 783,
 'ubisoftsupport': 784,
 "let's": 785,
 'hyped': 786,
 'favourite': 787,
 'including': 788,
 'close': 789,
 'head': 790,
 'dope': 791,
 'okay': 792,
 'sense': 793,
 'o': 794,
 'boy': 795,
 'redeeming': 796,
 'special': 797,
 'item': 798,
 'hold': 799,
 'break': 800,
 'wins': 801,
 'slow': 802,
 'box': 803,
 'version': 804,
 'page': 805,
 'option': 806,
 'summoners': 807,
 'unit': 808,
 'ridiculous': 809,
 'n': 810,
 'developers': 811,
 'franchise': 812,
 'sell': 813,
 'gotta': 814,
 'ai': 815,
 'congratulations': 816,
 '14': 817,
 'stuck': 818,
 'dear': 819,
 'delayed': 820,
 'af': 821,
 'true': 822,
 'crap': 823,
 'fast': 824,
 'history': 825,
 'enjoying': 826,
 'cancer': 827,
 'kind': 828,
 'sony': 829,
 'talking': 830,
 'plays': 831,
 'spend': 832,
 'fans': 833,
 'chinese': 834,
 'connection': 835,
 'social': 836,
 'fortnitegame': 837,
 'less': 838,
 'forever': 839,
 'kinda': 840,
 'welcome': 841,
 'valorant': 842,
 'plan': 843,
 '60': 844,
 'safe': 845,
 'stock': 846,
 'nfl': 847,
 'nba': 848,
 'star': 849,
 'poverty': 850,
 'sounds': 851,
 'edge': 852,
 'date': 853,
 'learning': 854,
 'calling': 855,
 '13': 856,
 'moments': 857,
 'decided': 858,
 'ball': 859,
 'plus': 860,
 'drive': 861,
 "isn't": 862,
 'enjoyed': 863,
 'takes': 864,
 'powerful': 865,
 "we're": 866,
 'absolute': 867,
 'test': 868,
 'log': 869,
 'wish': 870,
 'works': 871,
 'shooting': 872,
 'kids': 873,
 'selected': 874,
 'siege': 875,
 'fake': 876,
 'current': 877,
 'email': 878,
 'art': 879,
 'state': 880,
 'gpu': 881,
 'modern': 882,
 'football': 883,
 'shut': 884,
 'word': 885,
 'demon': 886,
 'odyssey': 887,
 'matter': 888,
 'longer': 889,
 'sea': 890,
 'performance': 891,
 'trial': 892,
 'beta': 893,
 'especially': 894,
 'companies': 895,
 '09': 896,
 'lose': 897,
 'website': 898,
 'bc': 899,
 'rest': 900,
 'white': 901,
 'couple': 902,
 'final': 903,
 'future': 904,
 'felt': 905,
 'sent': 906,
 'heard': 907,
 'eahelp': 908,
 'school': 909,
 '2016': 910,
 'dark': 911,
 'yourself': 912,
 'walmart': 913,
 'shitty': 914,
 'car': 915,
 'theft': 916,
 'ahead': 917,
 'j': 918,
 'controller': 919,
 '16': 920,
 'cry': 921,
 'anywhere': 922,
 'short': 923,
 'happens': 924,
 'created': 925,
 'features': 926,
 'geforce': 927,
 'fight': 928,
 'sweet': 929,
 'ask': 930,
 'added': 931,
 'quit': 932,
 'poor': 933,
 'voice': 934,
 'fantastic': 935,
 'program': 936,
 'government': 937,
 'china': 938,
 '70': 939,
 'report': 940,
 'defense': 941,
 'security': 942,
 'crashes': 943,
 'golden': 944,
 'hero': 945,
 'mut': 946,
 'between': 947,
 'decent': 948,
 'wonder': 949,
 'copy': 950,
 'behind': 951,
 'quality': 952,
 '25': 953,
 'pandemic': 954,
 'winning': 955,
 'cross': 956,
 'till': 957,
 'fixed': 958,
 'massive': 959,
 'quiz': 960,
 'feeling': 961,
 'told': 962,
 'fire': 963,
 'quick': 964,
 'wikipedia': 965,
 '24': 966,
 'fall': 967,
 'lately': 968,
 'turned': 969,
 'greatest': 970,
 'ios': 971,
 'within': 972,
 'hacked': 973,
 'packs': 974,
 'brand': 975,
 'happened': 976,
 'stops': 977,
 'suddenly': 978,
 'platform': 979,
 'loading': 980,
 'heart': 981,
 '50': 982,
 'toxic': 983,
 'offer': 984,
 'boring': 985,
 'pick': 986,
 'inside': 987,
 'gs': 988,
 'dog': 989,
 'towards': 990,
 'press': 991,
 'buff': 992,
 'low': 993,
 'hunter': 994,
 'didn’t': 995,
 'calls': 996,
 'shows': 997,
 'workers': 998,
 'awful': 999,
 'imo': 1000,
 ...}

In [98]:
tokenizer.document_count

8094

In [99]:
len(tokenizer.word_index)

14738

In [100]:
sequences=tokenizer.texts_to_sequences(data['Tweets'])

In [101]:
sequences

[[583, 12, 202, 1376, 223, 99, 187, 2069],
 [317,
  1886,
  3058,
  3696,
  196,
  34,
  1025,
  27,
  701,
  1089,
  1146,
  10,
  4813,
  7,
  4814,
  4,
  4815,
  147,
  15,
  266,
  219,
  433,
  9,
  1090,
  2,
  2674,
  7,
  1887,
  3059],
 [54],
 [154, 492, 27, 1215, 9, 88, 2331],
 [20,
  238,
  875,
  2675,
  3697,
  3060,
  32,
  2070,
  4816,
  163,
  112,
  13,
  128,
  7587,
  1602,
  252,
  98,
  2,
  2070,
  1603,
  246,
  26,
  238],
 [61, 58, 276, 445, 4, 2, 18],
 [90,
  7588,
  3698,
  1216,
  780,
  125,
  14,
  2,
  211,
  2332,
  7589,
  4817,
  17,
  1604,
  211,
  524,
  90,
  1217,
  240,
  4,
  7590,
  373,
  34,
  204,
  4,
  90,
  277,
  14,
  2332,
  2,
  4818],
 [7591, 15, 189, 27, 141, 802, 9, 2, 1729, 7, 7592],
 [117, 2, 92, 393, 118, 331, 374, 55, 82, 1091],
 [3, 63, 78, 187, 1026, 15, 755, 6, 48, 1147, 803, 10, 84, 239],
 [1027, 53, 3, 3061, 187],
 [97,
  524,
  26,
  702,
  50,
  1730,
  176,
  1292,
  2071,
  1605,
  37,
  2072,
  77,
  33,
  122,
  1148,
  641,
  62,
  62,
  2,
  2073,
  434,
  1218,
  1730,
  26,
  756,
  7593,
  113,
  318],
 [1731, 13, 3062, 7, 7594, 13, 1606, 4819, 6, 390, 337, 2, 259, 119],
 [46, 56, 839, 23, 9, 13, 981, 28, 12, 49, 62, 276, 840, 1376, 703, 62],
 [104,
  426,
  104,
  230,
  1732,
  115,
  469,
  105,
  29,
  4820,
  297,
  513,
  152,
  9,
  839,
  703,
  4821,
  297,
  31,
  7595,
  4822,
  7596,
  25,
  307,
  19,
  12,
  757,
  3699,
  88,
  7597,
  261,
  4823],
 [584, 71, 66, 192, 97, 41, 9],
 [683, 13, 7598, 172, 190, 7, 7599, 7600],
 [4824, 982, 11, 145, 684, 60, 79, 569, 4825, 3700, 4826, 1377, 40, 2676, 503],
 [47, 15, 504, 242, 32, 19, 6, 2072, 641, 3, 2333, 735, 15],
 [938,
  7601,
  44,
  44,
  5,
  1293,
  3063,
  2074,
  1294,
  7602,
  4827,
  17,
  135,
  1028,
  2677,
  7603,
  81,
  45,
  72,
  4828],
 [24, 736, 60, 545, 30, 103, 174, 7604, 2, 704, 1378, 40, 332],
 [4829, 4, 13, 675, 61, 289, 19, 12],
 [3,
  118,
  20,
  2678,
  38,
  155,
  12,
  352,
  219,
  319,
  55,
  115,
  290,
  127,
  160,
  20,
  3064],
 [122, 505, 326, 254, 5, 1607, 22, 939, 9, 18, 5, 10, 97, 167],
 [983, 3065, 906, 22, 7605, 2075, 4830, 1379, 129, 14, 79],
 [84, 470],
 [62, 538, 4831, 86, 247, 585, 5, 160, 737],
 [4832,
  2,
  48,
  193,
  10,
  54,
  7,
  123,
  136,
  2334,
  82,
  243,
  8,
  238,
  1608,
  222,
  23,
  4833,
  19,
  2,
  1380,
  7,
  327,
  2,
  320,
  8,
  308,
  4,
  143,
  2,
  230,
  97,
  27,
  176,
  59,
  5,
  59,
  150,
  119,
  184,
  5,
  3701,
  50,
  2,
  18],
 [2,
  7606,
  223,
  8,
  39,
  145,
  7607,
  30,
  1609,
  841,
  7608,
  282,
  137,
  7609,
  56,
  984,
  15,
  546,
  38,
  3702,
  82,
  249,
  40,
  192,
  7,
  205,
  462,
  99,
  77,
  842,
  14,
  1609,
  1149,
  146,
  10,
  2,
  738,
  1486,
  17,
  7610],
 [2076,
  1295,
  2077,
  7611,
  1733,
  8,
  319,
  2,
  83,
  168,
  178,
  907,
  9,
  6,
  280,
  57,
  321,
  7,
  15,
  16,
  42,
  182,
  3066,
  586,
  338,
  18,
  19,
  182,
  2335,
  843,
  2679,
  222,
  164,
  16,
  12,
  7612,
  8,
  1092,
  40,
  3,
  51,
  4834,
  12,
  4,
  13,
  4835,
  271,
  7,
  84,
  3067,
  5,
  243,
  12,
  56,
  657,
  59,
  4836,
  2078,
  7613,
  5],
 [506,
  756,
  3703,
  7614,
  9,
  3704,
  7615,
  7616,
  876,
  4837,
  7617,
  1150,
  3705,
  86,
  46,
  7618,
  375,
  2,
  7619,
  7,
  2,
  524,
  7620,
  3068,
  4838,
  3069,
  4839,
  198,
  570,
  86,
  161,
  108,
  463,
  6,
  704,
  9,
  4840,
  7621,
  2336,
  555,
  418,
  139],
 [29,
  68,
  7,
  138,
  27,
  22,
  3,
  94,
  3706,
  4841,
  5,
  272,
  2337,
  3070,
  38,
  2,
  115,
  30],
 [3,
  165,
  4,
  940,
  6,
  1093,
  97,
  2680,
  7622,
  1093,
  2338,
  4,
  4842,
  22,
  9,
  2,
  190,
  7,
  175,
  18,
  16,
  7623,
  705,
  8,
  7624,
  2681,
  1487],
 [755,
  7,
  2,
  260,
  179,
  7625,
  31,
  376,
  471,
  7626,
  51,
  525,
  9,
  1488,
  30,
  1489,
  7,
  59,
  130,
  844,
  3707,
  1296,
  486,
  2339,
  4,
  116,
  7627,
  17,
  2079,
  781,
  7628],
 [22,
  3,
  504,
  33,
  75,
  13,
  361,
  173,
  291,
  51,
  42,
  110,
  283,
  206,
  758,
  1610,
  337,
  120,
  6,
  173,
  5,
  25,
  33,
  1888,
  145,
  22,
  382,
  201,
  493,
  202,
  89],
 [507,
  207,
  2,
  177,
  101,
  87,
  153,
  31,
  1219,
  1611,
  514,
  4843,
  43,
  4,
  99,
  32,
  9,
  2080,
  35,
  36,
  17,
  7629],
 [144,
  165,
  4,
  347,
  150,
  193,
  706,
  307,
  10,
  877,
  168,
  539,
  739,
  413,
  377,
  1094,
  1381,
  7630],
 [472,
  1490,
  15,
  51,
  2340,
  189,
  7631,
  4844,
  24,
  84,
  10,
  6,
  7632,
  8,
  40,
  2341,
  40,
  11,
  8,
  985],
 [115,
  2081,
  1220,
  3,
  24,
  494,
  4,
  185,
  547,
  6,
  43,
  571,
  148,
  15,
  4,
  29,
  321,
  7,
  15,
  97,
  759,
  5,
  27,
  298,
  14,
  115,
  4845,
  5,
  2342,
  15,
  76,
  642,
  69,
  2343,
  11,
  4846,
  59,
  130,
  616,
  255,
  413,
  1491,
  39,
  78,
  11,
  29,
  572,
  21,
  69,
  339,
  1151,
  20,
  148,
  15],
 [1029, 133, 391, 7633, 7634, 91, 4847, 782, 7635],
 [3708, 6, 198, 487, 19, 203, 261, 2, 17],
 [74, 37, 84, 133, 375, 6, 1152, 173, 291, 2082],
 [80,
  1095,
  2,
  88,
  179,
  172,
  4,
  23,
  13,
  136,
  3071,
  1153,
  383,
  4848,
  17,
  135,
  1221,
  1297,
  4849,
  3709],
 [1889, 4, 90, 5, 93, 2, 2344, 7636, 2682, 5, 122, 2, 83, 740, 163, 233],
 [404,
  2083,
  194,
  22,
  19,
  2,
  7637,
  1382,
  3,
  2083,
  1298,
  61,
  268,
  111,
  15,
  7638,
  3710,
  11,
  47,
  74,
  1612,
  61,
  7639,
  404,
  32],
 [1030,
  7640,
  104,
  82,
  178,
  136,
  737,
  587,
  84,
  7641,
  2,
  4850,
  2345,
  7642,
  1890,
  1096,
  4851,
  101,
  87,
  153,
  1148,
  7,
  3711,
  2346,
  7,
  2,
  756,
  2084,
  7643,
  2347,
  3072,
  157,
  2683,
  22,
  7644,
  7645,
  7646,
  7647,
  7648,
  493],
 [7649,
  7650,
  24,
  93,
  2,
  878,
  629,
  845,
  29,
  5,
  162,
  10,
  219,
  238,
  10,
  2,
  2348,
  9,
  2,
  340,
  41,
  56,
  21,
  6,
  1097,
  73,
  135,
  5,
  2,
  238,
  4852,
  526],
 [19, 70, 7651, 50, 12],
 [9,
  7652,
  4853,
  879,
  7,
  299,
  2,
  7653,
  8,
  59,
  224,
  6,
  43,
  362,
  986,
  1613,
  1734,
  941,
  9,
  1735,
  3073],
 [49],
 [144,
  9,
  13,
  306,
  21,
  3,
  494,
  4,
  285,
  6,
  320,
  3074,
  20,
  131,
  28,
  114,
  86,
  2,
  2085,
  234,
  8,
  144,
  9,
  846,
  116,
  707],
 [7654,
  3712,
  445,
  4,
  135,
  5,
  80,
  708,
  6,
  942,
  193,
  4,
  117,
  6,
  7655,
  7656,
  9,
  480,
  760,
  8,
  7657,
  40,
  7658,
  135,
  7659,
  55,
  1614,
  7,
  66,
  2086,
  11,
  8,
  14,
  804,
  4854,
  805,
  7660,
  7661,
  80,
  17,
  709,
  106,
  7662,
  140],
 [90,
  2684,
  3713,
  137,
  1489,
  1098,
  14,
  15,
  103,
  7663,
  5,
  31,
  64,
  298,
  38,
  103,
  5,
  15,
  27,
  137,
  113,
  806,
  162,
  10,
  303],
 [1736,
  1737,
  3075,
  4855,
  1615,
  455,
  120,
  7664,
  1738,
  4856,
  3714,
  464,
  1492,
  14,
  7665,
  527,
  7666],
 [13, 3715, 880, 7667, 56, 2349, 90],
 [12, 2, 177, 57, 328, 3716, 13, 57, 14, 329, 3717],
 [12, 26, 710, 341, 22, 165, 4, 1299, 13, 881],
 [47,
  6,
  171,
  18,
  987,
  6,
  171,
  18,
  943,
  14,
  15,
  121,
  15,
  169,
  11,
  6,
  7668,
  3,
  208,
  4,
  169,
  3718,
  209,
  23,
  7669],
 [419, 419, 419, 419],
 [176, 60, 262, 446, 38, 528, 8, 2, 414, 240, 4, 33],
 [2350,
  7670,
  162,
  10,
  137,
  1031,
  4,
  456,
  807,
  183,
  2,
  171,
  4,
  98,
  47,
  15,
  353,
  6,
  296,
  79,
  643,
  292,
  685,
  1099,
  16,
  10,
  195,
  486,
  354,
  4,
  214,
  42,
  988,
  99,
  711,
  39,
  10,
  6,
  214,
  231,
  104,
  10,
  944,
  2087,
  808,
  2350,
  81,
  45,
  72,
  7671],
 [84,
  9,
  2,
  376,
  68,
  3719,
  7,
  190,
  7,
  175,
  8,
  20,
  2088,
  84,
  9,
  2,
  376,
  68,
  18,
  7,
  190,
  7,
  175,
  8,
  20,
  1222,
  84,
  9,
  2,
  376,
  68,
  3719,
  7,
  4857,
  7,
  175,
  8,
  20,
  2088,
  84,
  1493,
  2,
  376,
  68,
  3719,
  7,
  190,
  7,
  175,
  8,
  145,
  2088],
 [435, 847, 260, 261, 132, 465, 89, 984, 3720, 2351, 1300, 4, 7672],
 [184, 473, 4, 23, 95, 120, 308, 66, 3, 63],
 [848,
  436,
  4,
  4858,
  5,
  1154,
  12,
  86,
  11,
  202,
  37,
  7673,
  8,
  92,
  220,
  989,
  35,
  36,
  17,
  7674],
 [338, 132],
 [1155,
  7,
  7675,
  285,
  2089,
  1156,
  4,
  712,
  1616,
  375,
  44,
  44,
  7676,
  540,
  3076,
  7,
  469],
 [293,
  1617,
  3,
  63,
  34,
  82,
  1032,
  190,
  7,
  175,
  8,
  54,
  7,
  13,
  29,
  57,
  7677,
  82,
  3,
  24,
  63,
  11,
  182,
  354,
  3,
  252,
  366,
  1494,
  6,
  162,
  470],
 [601, 256, 11, 19, 2, 539, 405],
 [20, 602, 7, 13, 48, 4859, 7678, 3077],
 [2, 177, 945, 7, 367, 175, 26, 6, 1495, 2352, 7679, 11, 7680, 81, 72, 7681],
 [1301, 87, 23, 3078, 4, 22, 24, 1033, 3, 93, 6, 79, 7682, 14],
 [8,
  946,
  232,
  333,
  215,
  908,
  126,
  686,
  946,
  286,
  4,
  143,
  849,
  7,
  2,
  119,
  7683,
  1739,
  5,
  277,
  176,
  2,
  435,
  391,
  713,
  14,
  232,
  235,
  290,
  35,
  1034,
  7684],
 [11, 8, 25, 2, 128, 57, 16, 2, 541, 741, 52, 555, 249, 6, 630],
 [3721, 148, 3079, 236, 2685, 14, 7685, 9, 2, 394, 299],
 [174,
  742,
  1891,
  27,
  486,
  83,
  4,
  101,
  525,
  3722,
  1035,
  415,
  9,
  30,
  644,
  91,
  7686],
 [264,
  61,
  228,
  284,
  714,
  2686,
  19,
  2,
  18,
  383,
  2353,
  4,
  21,
  6,
  2354,
  3723,
  323,
  2355,
  3080,
  3724,
  3725,
  3726,
  455,
  4860,
  427,
  1892,
  52,
  2687,
  322,
  31,
  2356,
  77,
  368,
  164,
  75,
  157,
  94,
  573,
  7687,
  112,
  2,
  232],
 [225,
  139,
  8,
  1496,
  9,
  1618,
  62,
  4,
  241,
  284,
  447,
  123,
  2357,
  9,
  12,
  89,
  740,
  73,
  4861,
  455,
  909],
 [783, 328, 3727, 1893],
 [41, 208, 6, 1223, 10, 416, 212, 437],
 [24,
  761,
  472,
  2688,
  215,
  2,
  1383,
  4,
  33,
  14,
  2,
  4862,
  78,
  7688,
  6,
  292,
  18,
  26,
  4,
  324,
  1384,
  4863,
  74,
  20,
  4864,
  4,
  98],
 [3,
  152,
  12,
  448,
  171,
  14,
  79,
  366,
  67,
  542,
  10,
  6,
  1157,
  4,
  214,
  449,
  503,
  79,
  9,
  18,
  428,
  7689],
 [126,
  109,
  9,
  12,
  229,
  193,
  404,
  1894,
  2,
  3081,
  474,
  215,
  46,
  513,
  69,
  16,
  240,
  12,
  338,
  157,
  438,
  2,
  18,
  53,
  15,
  51,
  24,
  447,
  14,
  6,
  7690,
  183,
  5,
  525,
  120,
  132,
  1302],
 [30,
  2,
  283,
  57,
  529,
  2,
  392,
  16,
  102,
  27,
  457,
  67,
  296,
  439,
  64,
  617,
  618,
  2,
  850,
  474,
  136,
  7,
  110,
  49,
  25,
  21,
  263,
  4,
  250,
  495,
  5,
  49,
  25,
  21,
  263,
  4,
  250,
  254,
  196,
  136,
  7,
  110,
  49,
  25,
  21,
  263,
  4,
  250,
  254],
 [1740,
  102,
  8,
  60,
  3082,
  3069,
  1895,
  10,
  3728,
  3729,
  4865,
  7691,
  9,
  2,
  1619,
  2689,
  252,
  11,
  23,
  1036,
  16,
  7692,
  112,
  455,
  7693,
  94,
  990,
  2,
  427,
  7,
  2,
  2689,
  173,
  8,
  7694,
  77,
  122,
  215,
  4,
  2,
  1158,
  3068,
  1294,
  7695,
  150,
  1035,
  8,
  7696,
  645,
  133,
  7697,
  3730,
  4,
  363,
  230],
 [2],
 [61,
  9,
  6,
  548,
  880,
  7,
  658,
  212,
  39,
  28,
  3,
  21,
  4,
  185,
  11,
  26,
  1303,
  61,
  323,
  278,
  50,
  743,
  107,
  14,
  19,
  1100,
  212,
  39,
  3,
  334,
  54,
  119,
  475,
  23,
  6,
  406,
  7,
  11,
  29,
  66,
  6,
  4866,
  35,
  85,
  17,
  4867],
 [162, 264, 10, 1741, 22, 188, 6, 416, 18, 19, 55, 1385, 7698, 3731],
 [2, 92, 111, 713, 30, 2, 314, 7, 12, 8, 1741, 22],
 [910,
  26,
  249,
  6,
  43,
  173,
  10,
  82,
  2358,
  187,
  191,
  91,
  4868,
  31,
  911,
  1896,
  68,
  2690,
  132,
  3732,
  31,
  323,
  742,
  420,
  198,
  4869,
  1897,
  6,
  1497,
  173],
 [149,
  515,
  149,
  450,
  24,
  1742,
  248,
  38,
  15,
  5,
  144,
  684,
  38,
  34,
  476,
  315,
  407,
  122,
  25,
  9,
  1224,
  49,
  3,
  33,
  4,
  1037,
  13,
  244,
  387,
  7699,
  12,
  8,
  809],
 [154,
  172,
  784,
  15,
  51,
  15,
  189,
  707,
  810,
  117,
  12,
  48,
  7700,
  18,
  408,
  2,
  3733,
  3734,
  1038,
  70,
  2359,
  2,
  762,
  18,
  763,
  73,
  16,
  29,
  2691,
  687,
  11,
  76,
  112,
  20,
  124,
  28,
  3,
  51,
  76,
  16,
  45,
  42,
  603],
 [785,
  29,
  1225,
  4,
  588,
  395,
  2,
  3735,
  85,
  631,
  5,
  111,
  3083,
  16,
  4870,
  32,
  147,
  373,
  64,
  455,
  7701,
  5,
  7702,
  129,
  744,
  12,
  8,
  134,
  715,
  1498,
  14,
  1620,
  106,
  845],
 [1743,
  409,
  47,
  15,
  27,
  25,
  604,
  4,
  619,
  3084,
  326,
  49,
  11,
  2360,
  811,
  34,
  3736,
  333,
  27,
  215,
  3737,
  646,
  28,
  15,
  33,
  204,
  38,
  3084,
  20,
  122,
  505],
 [440,
  384,
  7703,
  440,
  384,
  4871,
  66,
  2,
  2692,
  21,
  46,
  257,
  4,
  2,
  2090,
  7704,
  14,
  2,
  3738,
  7705,
  12,
  8,
  75,
  157,
  37,
  216,
  46,
  1621,
  19,
  327,
  16,
  1386,
  530,
  440,
  384,
  4871],
 [12,
  2693,
  8,
  146,
  3,
  63,
  1499,
  4872,
  605,
  19,
  2,
  1101,
  14,
  11,
  53,
  11,
  24,
  1095,
  4,
  185,
  16,
  13],
 [7706,
  24,
  463,
  115,
  68,
  38,
  13,
  2694,
  400,
  34,
  2695,
  659,
  659,
  51,
  76,
  14,
  45,
  716,
  142,
  4,
  194,
  324,
  2,
  496],
 [1744, 3, 51, 76, 45, 142, 10, 163, 13, 79, 2361],
 [79,
  168,
  24,
  1304,
  6,
  1887,
  574,
  22,
  203,
  4873,
  3085,
  17,
  135,
  1102,
  1297,
  1898],
 [66, 41, 63, 212, 39, 4874, 104, 1745, 297, 62, 99, 187],
 [150,
  57,
  396,
  42,
  7707,
  417,
  22,
  3,
  688,
  2,
  548,
  660,
  53,
  3,
  26,
  229,
  4,
  217,
  4875,
  2091,
  7,
  2,
  647,
  9,
  2,
  41,
  27,
  191,
  91,
  1039,
  137,
  647,
  171,
  396,
  17,
  82,
  7708],
 [3739, 236, 43, 10, 2, 7709],
 [4, 4876, 2696, 9, 101, 87, 153, 31, 151, 125, 3740, 4877],
 [414, 3086, 7710, 4878, 136, 4879, 1387],
 [1305,
  405,
  83,
  309,
  1622,
  50,
  589,
  458,
  13,
  658,
  4880,
  15,
  114,
  83,
  1622,
  10,
  882,
  717,
  40,
  590,
  9,
  169,
  7,
  237,
  190,
  209,
  23,
  7711,
  7712],
 [91, 3, 63, 54, 198, 35, 36, 17, 4881],
 [66, 11, 185, 110, 471, 56, 3087, 19, 11, 199, 98, 11, 71, 176, 339, 62],
 [154,
  267,
  75,
  49,
  46,
  277,
  176,
  2,
  3741,
  620,
  718,
  37,
  4882,
  246,
  621,
  620,
  3,
  222,
  575,
  1899,
  4883,
  1899,
  570,
  851,
  37,
  247,
  415,
  38,
  54,
  2092,
  53,
  247,
  195,
  2,
  113,
  240,
  4,
  117,
  11,
  1900,
  8,
  4,
  362,
  1623,
  2,
  1624],
 [3,
  222,
  144,
  661,
  3742,
  4,
  715,
  2697,
  2698,
  1625,
  30,
  241,
  576,
  111,
  10,
  1500],
 [66, 6, 419, 119, 32, 3, 114, 142, 4, 629, 3088, 5, 42, 192, 7, 205],
 [355, 508],
 [1030,
  4884,
  79,
  5,
  4885,
  62,
  414,
  4886,
  2335,
  7713,
  17,
  4887,
  3089,
  7714,
  4888,
  4889,
  62,
  7715,
  3090,
  7716,
  4890,
  4891,
  4892,
  1381],
 [6,
  7717,
  1501,
  4893,
  4,
  226,
  15,
  188,
  6,
  352,
  7,
  400,
  80,
  3091,
  591,
  10,
  286,
  4,
  4894,
  2,
  756,
  7718,
  9,
  34,
  704],
 [7719, 27, 2, 355, 234, 16, 51, 1502, 9, 6, 394, 299, 947, 7720, 5, 7721],
 [154, 182, 1901, 14, 176, 211, 1902, 481, 7722, 5, 70, 326, 21, 182],
 [3,
  108,
  6,
  287,
  59,
  57,
  4,
  42,
  2699,
  127,
  5,
  2,
  59,
  3,
  42,
  2,
  18,
  2,
  59,
  4895,
  3,
  118,
  16,
  12,
  18,
  8,
  2,
  229,
  210,
  234],
 [16, 2, 229, 1503, 56, 42, 92, 133],
 [191, 68, 1903, 5, 6, 191, 683, 3739, 23, 20, 289, 54, 119],
 [80, 7723, 466, 14, 745, 2093, 4, 2, 1384, 7724, 17, 80, 7725],
 [84,
  133,
  19,
  13,
  648,
  577,
  93,
  272,
  128,
  883,
  2700,
  375,
  22,
  5,
  70,
  300,
  224,
  353,
  76,
  45,
  884,
  65],
 [68, 100, 89, 18, 15, 93, 1626, 746, 117, 11, 35, 36, 17, 7726],
 [31,
  8,
  571,
  1746,
  40,
  3,
  213,
  63,
  2701,
  1504,
  145,
  181,
  3,
  513,
  152,
  105,
  7,
  110,
  120,
  16,
  719,
  54,
  202,
  948,
  703],
 [4896,
  1103,
  12,
  18,
  344,
  33,
  182,
  59,
  546,
  120,
  2,
  1388,
  55,
  949,
  12,
  18,
  26,
  6,
  3743],
 [12,
  8,
  6,
  362,
  54,
  86,
  689,
  20,
  4897,
  3,
  56,
  366,
  4,
  7727,
  587,
  207,
  321,
  720,
  2362,
  7728,
  7729],
 [2, 83, 3744],
 [1104,
  160,
  268,
  23,
  20,
  4898,
  47,
  1627,
  73,
  781,
  4899,
  1226,
  14,
  2,
  1159,
  11,
  4900,
  414],
 [7730, 83, 592, 2702, 1628, 108, 2, 1029, 662, 7, 74, 1160, 812],
 [4901,
  707,
  1496,
  216,
  3,
  224,
  63,
  631,
  591,
  24,
  37,
  4902,
  5,
  4903,
  29,
  7,
  34,
  388,
  3,
  21,
  3,
  593,
  7731,
  5,
  3,
  63,
  11,
  37,
  3,
  63,
  216,
  3,
  4904,
  3,
  25,
  21,
  6,
  465,
  77,
  6,
  211,
  88,
  77,
  6,
  663,
  3092,
  3,
  113,
  2703,
  21,
  25,
  6,
  593,
  5,
  3,
  51,
  25,
  33,
  16,
  216,
  19,
  707,
  1496,
  11,
  3,
  2704,
  15,
  109,
  707],
 [1227, 235, 80, 852, 7732, 1747, 9, 378, 3745, 408, 1893, 17, 2094, 764],
 [310, 279, 63],
 [3, 118, 296, 118, 1904, 268, 813, 12, 159, 40, 397, 40, 11, 1040],
 [25, 113, 330, 85, 1629, 34, 853, 28, 74, 145, 89, 10, 1905],
 [4905,
  225,
  463,
  587,
  6,
  950,
  7,
  115,
  68,
  18,
  421,
  2,
  238,
  4,
  1219,
  53,
  4906,
  4907,
  11,
  310,
  531,
  11],
 [1220,
  115,
  118,
  41,
  632,
  12,
  58,
  2705,
  109,
  7733,
  22,
  160,
  140,
  160,
  176,
  3746,
  196,
  2,
  427,
  1505,
  27,
  2706,
  46,
  1748,
  5,
  102,
  266,
  1228,
  29,
  605,
  75,
  8,
  12,
  6,
  234],
 [3093, 4908],
 [96, 578, 450, 133, 783, 328, 4909, 4910, 3094],
 [3, 56, 144, 661, 3742, 4, 715, 2697, 2698, 1625, 30, 111, 5, 206, 10, 1500],
 [84, 133, 8, 224, 2, 83, 130, 107, 4, 42, 7734, 9, 1506, 200],
 [2,
  1041,
  951,
  29,
  50,
  29,
  179,
  193,
  112,
  2707,
  193,
  39,
  2095,
  1037,
  991,
  288,
  17,
  2079,
  168,
  88,
  135,
  81,
  45,
  72,
  4911],
 [721,
  4912,
  4913,
  7735,
  44,
  369,
  11,
  108,
  1900,
  1389,
  122,
  4914,
  377,
  765,
  4915,
  269,
  4916,
  81,
  45,
  72,
  4917],
 [12,
  168,
  50,
  2,
  116,
  3095,
  179,
  8,
  2,
  136,
  449,
  178,
  590,
  50,
  389,
  29,
  173,
  35,
  36,
  17,
  7736],
 [633,
  218,
  26,
  1229,
  786,
  10,
  514,
  3747,
  2,
  1161,
  641,
  5,
  2708,
  2,
  18,
  40,
  397,
  301,
  3,
  252,
  5,
  49,
  3,
  538,
  4918,
  2096,
  12,
  267,
  31],
 [2,
  579,
  406,
  8,
  16,
  102,
  27,
  217,
  59,
  7737,
  7738,
  130,
  2363,
  5,
  2363,
  246,
  7739,
  4,
  221,
  9,
  59,
  7740,
  4919,
  5,
  46,
  4920,
  106,
  29],
 [196,
  3,
  76,
  642,
  69,
  84,
  12,
  18,
  10,
  3096,
  1906,
  197,
  3,
  76,
  322,
  676,
  1390,
  7,
  11],
 [172, 80, 480, 952, 1033, 3, 157, 21, 6, 316, 35, 36, 17, 7741],
 [6],
 [7742,
  8,
  13,
  2364,
  7,
  1749,
  4921,
  4922,
  2365,
  9,
  422,
  190,
  19,
  6,
  3748,
  7743,
  223,
  396,
  7744,
  126,
  686,
  946],
 [462, 1630, 2, 96, 65, 467, 41, 21, 6, 664, 4, 3097, 100, 35, 36, 17, 7745],
 [1150,
  132,
  688,
  20,
  15,
  21,
  145,
  231,
  263,
  4,
  747,
  7,
  89,
  80,
  477,
  15,
  51,
  324,
  19,
  53,
  34,
  854,
  38,
  103,
  138,
  2097,
  758,
  51,
  2366,
  29,
  15,
  59,
  9,
  308,
  24,
  16,
  273,
  172,
  269,
  3749],
 [4923,
  2709,
  15,
  319,
  326,
  254,
  28,
  51,
  15,
  49,
  109,
  109,
  194,
  912,
  32,
  123,
  383,
  230,
  5,
  163,
  1306,
  417,
  154,
  2710,
  4,
  49,
  248,
  50,
  7746,
  86,
  99,
  573,
  45,
  22,
  46,
  27,
  308,
  310,
  303,
  109,
  194,
  106,
  46,
  556,
  76,
  1162,
  45,
  722,
  4,
  106,
  6,
  1750,
  37,
  22,
  246,
  8,
  677,
  459],
 [460,
  1391,
  594,
  195,
  497,
  75,
  12,
  877,
  1895,
  990,
  221,
  315,
  8,
  1042,
  25,
  4924],
 [11, 26, 7747, 97, 8, 2, 3098, 1307, 3750, 30, 16, 85],
 [2367, 782, 7, 45, 311],
 [47, 113, 2, 4925, 9, 2711, 227, 1163, 43],
 [482, 913, 79, 8, 107, 4, 96, 15, 19, 1089],
 [80,
  885,
  39,
  3751,
  361,
  7748,
  120,
  2,
  1392,
  40,
  60,
  634,
  2,
  2712,
  992,
  269,
  4926,
  81,
  72,
  4927],
 [3099,
  17,
  1907,
  1393,
  7749,
  4928,
  472,
  4929,
  4930,
  12,
  549,
  2368,
  886,
  2369,
  3,
  24,
  233,
  11,
  9,
  2,
  128,
  57,
  5,
  11,
  330,
  1394,
  181],
 [578, 163, 42, 382, 201, 1395, 321, 82, 266, 20, 124],
 [9],
 [80,
  155,
  557,

In [102]:
len(sequences[2])

1

In [103]:
from keras.utils import pad_sequences

In [104]:
sequences=pad_sequences(sequences, padding='pre')

In [105]:
sequences

array([[   0,    0,    0, ...,   99,  187, 2069],
       [   0,    0,    0, ...,    7, 1887, 3059],
       [   0,    0,    0, ...,    0,    0,   54],
       ...,
       [   0,    0,    0, ...,  173,  149,  515],
       [   0,    0,    0, ...,   81, 1994, 7565],
       [   0,    0,    0, ..., 3067, 4522, 3952]],
      shape=(8094, 74), dtype=int32)

In [106]:
from tensorflow.keras.layers import SimpleRNN, Dense,Input, Embedding
from tensorflow.keras.models import Sequential

In [107]:
X=sequences
Y=data['Sentiment'].values

In [108]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

In [109]:
model=Sequential()

In [110]:
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [111]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [112]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [113]:
model.fit(X_train,Y_train,epochs=10,validation_data=(X_test,Y_test),batch_size=64)

Epoch 1/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.3626 - loss: 1.0992 - val_accuracy: 0.3626 - val_loss: 1.0908
Epoch 2/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.3665 - loss: 1.0934 - val_accuracy: 0.3638 - val_loss: 1.0888
Epoch 3/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.3707 - loss: 1.0942 - val_accuracy: 0.3626 - val_loss: 1.0890
Epoch 4/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3703 - loss: 1.0932 - val_accuracy: 0.3644 - val_loss: 1.0919
Epoch 5/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3748 - loss: 1.0926 - val_accuracy: 0.3687 - val_loss: 1.0913
Epoch 6/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3686 - loss: 1.0923 - val_accuracy: 0.3632 - val_loss: 1.0928
Epoch 7/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.3693 - loss: 1.0935 - val_accuracy: 0.3743 - val_loss: 1.0920
Epoch 8/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.3603 - loss: 1.0934 - val_accuracy: 0.3650 - val_loss: 1.0968
Epoch 9/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3731 - loss: 1.0933 - val_accuracy: 0.3644 - val_loss: 1.0941
Epoch 10/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3673 - loss: 1.0930 - val_accuracy: 0.3657 - val_loss: 1.0908